### ISSUE TITLE
Trip History on User Profile not Displaying Trips

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#266]
On my local, I also noticed now that the list of past trips isn't populating.

<img width="360" alt="screen shot 2017-02-17 at 9 50 07 am" src="https://cloud.githubusercontent.com/assets/4267904/23077831/159e9b8c-f514-11e6-8588-9827cf0d8cf3.png">

**Comment by giovanniorigins** [comment]
woah, on it

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/17/17 - 02/17/17
Work session total: 0:00:31
Grand total: 0:00:31
