### ISSUE TITLE
Server Validation Errors Should Display in Vue Components

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#272]
There appear to be several scenarios where a server-side validation fails but no detailed error message is returned to the user in the vue component.

Some things include:
- invalid or declined Credit Cards
- invalid passport number (must be 9 characters long)

```json
errors: { number: ["The number must be at least 9 characters."] }
message: "422 Unprocessable Entity"
status_code: 422
```

I'm sure there are more. Maybe we can write some kind of mixin to add to our components to show these errors that get pass the initial vue validation?

**Comment by giovanniorigins** [comment]
Initially 
i was going to say we can't use a mixin, but this morning i had a great idea using a comvbination of a mixin and directive

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/17/17 - 02/19/17
Work session total: 7:16:31
Grand total: 7:16:31

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/20/17 - 02/20/17
Work session total: 5:41:55
Grand total: 12:58:26
