### ISSUE TITLE
Groups and trip options cards have layout issues

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#275]
Needs some flexbox love <3
<img width="1292" alt="screen shot 2017-02-17 at 10 40 46 am" src="https://cloud.githubusercontent.com/assets/4267904/23084126/d49c461e-f52e-11e6-9735-0bd99f9e81c5.png">

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/18/17 - 02/19/17
Work session total: 2:10:21
Grand total: 2:10:21

**Comment by giovanniorigins** [comment]
Will need to add classes and media queries to better manage flexbox sections

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/20/17 - 02/20/17
Work session total: 0:01:04
Grand total: 2:11:25

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/21/17 - 02/21/17
Work session total: 0:19:07
Grand total: 2:30:32
