### ISSUE TITLE
Add markdown instructions for user reference

### ISSUE THREAD

**Issue by giovanniorigins** [missions-me/missions#283]
Users and Admins need a way to know of all( or some ) of the possibilities of markdown syntax via examples.

**Comment by nkeena** [comment]
I recommend giving users just the basics like headings, lists, bold, and italic. I think we should avoid more complex things like images, links, and tables for now.

**Comment by giovanniorigins** [comment]
Agreed, I'm thinking of using a modal that toggles syntax and example so they can see the syntax in action.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/21/17 - 02/21/17
Work session total: 2:25:47
Grand total: 2:25:47
