### ISSUE TITLE
"Add Social Links" Marked as complete when there are no links

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#290]
<img width="958" alt="screen shot 2017-02-24 at 2 46 22 pm" src="https://cloud.githubusercontent.com/assets/4267904/23318387/30d81bd0-faa0-11e6-9b49-e1f18bed507e.png">

**Comment by nkeena** [comment]
PR #294 fixes this issue

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/24/17 - 02/24/17
Work session total: 0:07:29
Grand total: 0:07:29
