### ISSUE TITLE
User birthday saving incorrectly on signup form

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#291]
After creating a an account with a birthday of July 28, 1987 I went into my settings and saw my birthday as September 20, 1987. Was also saved incorrectly in the database.

The issue may be when the date string is converted into a date object in the vue component before being sent to the API.

**Comment by nkeena** [comment]
PR #294 fixes this issue

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/24/17 - 02/24/17
Work session total: 0:09:47
Grand total: 0:09:47
