### ISSUE TITLE
Country select not populating with authenticated user's country

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#292]
If a user has set their country in settings, it should populate the trip registration form in the `basic-info.vue` component.

I already fixed several other fields that were not populating. The country code is being returned but not being converted to the `countryCodeObj` needed for the `v-select`

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/24/17 - 02/24/17
Work session total: 0:16:31
Grand total: 0:16:31

**Comment by nkeena** [comment]
PR #296 fixes Issue #292

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/25/17 - 02/25/17
Work session total: 0:13:32
Grand total: 0:30:03
