### ISSUE TITLE
Sponsor a Project form is no longer working

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#297]
Necessary changes to API broke this component.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/25/17 - 02/25/17
Work session total: 0:11:53
Grand total: 0:11:53

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/26/17 - 02/26/17
Work session total: 0:20:00
Grand total: 0:31:53

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/02/17 - 03/02/17
Work session total: 0:10:00
Grand total: 0:41:53
