### ISSUE TITLE
Admin Project Components Broken by API Changes

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#298]

**Comment by nkeena** [comment]
Breaking changes:

* Costs are no longer assigned to project initiatives
* Costs get assigned directly to projects
* Deadlines are no longer assigned to project initiatives
* Deadlines get assigned directly to projects

What needs debugging:

* Any reference or attempt to attach costs to initiatives should be removed from components. 
* API validation should be updated if needed.
* API transformer classes should be updated if needed.
* API `store` and `update` methods should be updated with appropriate post and push data.
* API filter classes should be tested and updated to match valid filters (i.e. query scopes)

What needs to be added:

* The `deadline-manager` component should be added to it's own tab under a project in the admin

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/02/17 - 03/02/17
Work session total: 0:42:30
Grand total: 0:42:30
