### ISSUE TITLE
Make user records "read only" for admins

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#299]
No edit or delete routes have been setup for admins, so records should be read only

**Comment by nkeena** [comment]
@giovanniorigins We simply need to hide the edit and delete icons on a "record" card (i.e passport, visa, etc.) only when the component is being viewed from an admin screen. `/admin`. I believe I created a simple helper mixin that can grab the first url parameter if you choose to do it that way.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/28/17 - 03/01/17
Work session total: 0:25:30
Grand total: 0:25:30

**Comment by nkeena** [comment]
@giovanniorigins Edit/Delete buttons are not showing up in the dashboard either.

I have noticed problems with the name overlapping these icons. Can we permanently remove the edit icon and just leave the delete icon.
