### ISSUE TITLE
Trip facilitator component not displaying

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#300]
The component is registered but not displaying on the admin and dashboard trip details pages. 

Encountering multiple errors:

```
[Vue warn]: Invalid expression. Generated function body:  { value:scope.user_id, client:'user','server: 'scope.user_id'}
```

```
Uncaught TypeError: Cannot read property 'handle' of undefined
```

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/25/17 - 02/25/17
Work session total: 0:09:10
Grand total: 0:09:10
