### ISSUE TITLE
PCI Compliance [3]

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#312]
To provide feedback on your PCI compliance questions:

The good news is that our default integration (Stripe Elements) avoids any of the previous concerns around iFrames, so Missions.me will be good to go on just needing the minimum SAQ requirements (not the full SAQ A-EP). 

All Stripe users must be compliant with the PCI Data Security Standards (PCI DSS). Businesses using Stripe Elements to collect payment details are eligible for the simplest PCI validation method, Self-Assessment Questionnaire A (SAQ A). Stripe Elements hosts all form inputs containing card data and is served from Stripe's domain.

As long as you serve your payment pages over TLS, and use either Stripe Elements or Stripe Checkout as the only way of handling card information, Stripe automatically creates a combined SAQ A and Attestation of Compliance (AOC) for you. This pre-filled document is available in your account’s dashboard. 

Alternatively, if you are using Stripe.js (which was the published default integration until we launched Elements), the migration process to Elements is very simple and we have documented the transition here: https://stripe.com/docs/elements/migrating

**Comment by nkeena** [comment]
@jgiovanni, I can't seem to complete the second step.  Clicking "next" results in no response. I don't see any errors or warnings in the console either.

Also, I don't receive any error message for an invalid card number or missing fields (other than card number).

**Comment by jgiovanni** [comment]
Components needing Stripe Elements Integration
- [ ] Donate
- [ ] Admin Transaction Form

**Comment by nkeena** [comment]
Getting these errors now on the donation component:
![screen shot 2017-09-20 at 4 53 56 pm](https://user-images.githubusercontent.com/4267904/30672948-8d09f87e-9e24-11e7-80d1-f21208a0dce7.png)

![screen shot 2017-09-20 at 4 54 09 pm](https://user-images.githubusercontent.com/4267904/30672954-8f0161c6-9e24-11e7-8cc0-4461e9009623.png)

![screen shot 2017-09-20 at 4 54 42 pm](https://user-images.githubusercontent.com/4267904/30672956-9138e2d4-9e24-11e7-9be5-9ed0c5adbdf9.png)

![screen shot 2017-09-20 at 4 55 03 pm](https://user-images.githubusercontent.com/4267904/30672958-96bcafba-9e24-11e7-9ee1-ad1abb7c32ad.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/20/17 - 09/20/17
Work session total: 4:35:48

Grand total: 4:35:48

**Comment by nkeena** [comment]
Spinner won't deactivate after an error message displays...

![screen shot 2017-09-21 at 4 45 14 pm](https://user-images.githubusercontent.com/4267904/30723498-af0d8f30-9eec-11e7-8317-4e9f2bbf8377.png)
![screen shot 2017-09-21 at 4 45 48 pm](https://user-images.githubusercontent.com/4267904/30723497-af0c2d70-9eec-11e7-9660-b2fd69fb2824.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/21/17 - 09/21/17
Work session total: 1:37:15

Grand total: 6:13:03
