### ISSUE TITLE
Invalid date error when updating a payment with upfront due date

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#319]
Looks like the string "invalid date" is being passed in the request. Server side validation is catching it because it expects it to be a date or for the "due_at" field not to be present.

```
{
"id":"329e962b-cdf6-454d-a255-e15afb8efa8c",
"amount_owed":200,
"percent_owed":100,
"due_at":"Invalid date", // problem right here
"grace_period":0,
"upfront":true
}
```

**Comment by nkeena** [comment]
PR #320 fixes this

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/09/17 - 03/09/17
Work session total: 1:03:37
Grand total: 1:03:37
