### ISSUE TITLE
Admin Transactions List not saving fields list

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#321]
The fields selected by the user are not persisting in local storage or being overwritten. I see the local storage `AdminTransactionListConfig` being updated, but when I refresh the page that key store gets reset to the defaults.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/09/17 - 03/09/17
Work session total: 0:17:02
Grand total: 0:17:02
