### ISSUE TITLE
Admin trips pages keep scrolling down on refresh

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#322]
On each tab, when the page loads, it seems to automatically scroll down to where a vue component is located.

See screen recording:
http://g.recordit.co/q859NwCJCC.gif

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/09/17 - 03/09/17
Work session total: 0:49:57
Grand total: 0:49:57

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:04:36
Grand total: 0:54:33
