### ISSUE TITLE
Influencer Credentials

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#325]
As a user, I would like to complete a questionnaire to submit my influencer credentials in order to satisfy my reservation's travel requirement.

**Comment by nkeena** [comment]
### Questions Needed:
Are you comfortable speaking in both a faith-based and non-faith based environments? Please explain.
[ short answer ]

Do you have prior experience speaking to a large audience? Please explain.
[ short answer ]

Have you ever spoken with a translator?
[ yes or no ]

Please list any degrees or certifications you hold and the issuing university.
[ short answer ]

Please tell us about your professional history including career highlights and current or past roles.
[ short answer ]

What areas would you consider yourself an expert?
[ short answer ]

Please list 3-4 topics that you would be most comfortable speaking on to college students? (i.e. technology, education, leadership, business, politics, etc.)
[ short answer ]

Please upload a bio or resume for review.
[ file upload (pdf only) ]

**Comment by nkeena** [comment]
Could probably use the `essay-update-create` component. Need a way to change the "subject" (i.e. testimony, influencer application), and introduce an uploads relationship.

I'm also beginning to think that renaming these from essays to questionaries.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/13/17 - 03/13/17
Work session total: 0:57:13
Grand total: 0:57:13

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/14/17 - 03/15/17
Work session total: 0:26:54
Grand total: 1:24:07

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/15/17 - 03/15/17
Work session total: 0:28:18
Grand total: 1:52:25

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/20/17 - 03/20/17
Work session total: 2:32:57
Grand total: 4:25:22

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/22/17 - 03/22/17
Work session total: 0:05:12
Grand total: 4:30:34

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/23/17 - 03/23/17
Work session total: 0:00:17
Grand total: 4:30:51

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/24/17 - 03/24/17
Work session total: 1:07:55
Grand total: 5:38:46

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/25/17 - 03/25/17
Work session total: 0:08:11
Grand total: 5:46:57

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/26/17 - 03/26/17
Work session total: 0:09:43
Grand total: 5:56:40

**Comment by nkeena** [comment]
@giovanniorigins can you also send an array of all upload_ids that are associated with the influencer credential? Trying to parse through an array of `content` looking for upload IDs could be difficult and potentially prone to bugs.

With an array of `upload_ids`, I can easily create create the relationship.

**Comment by giovanniorigins** [comment]
@nkeena okay, might want to add this to medical credentials also

**Comment by giovanniorigins** [comment]
@nkeena done!

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/27/17 - 03/27/17
Work session total: 0:10:38
Grand total: 6:07:18
