### ISSUE TITLE
Media Professional Credentials

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#326]
As a user I would like to complete a questionnaire form in order to satisfy my travel requirement to provide credentials as a media professional.

**Comment by nkeena** [comment]
Some thoughts regarding content:

Label:
**Please select any roles you have experience in and feel confident performing on this trip:**

Checkboxes:  (at least one is required)
+ Videographer
+ Photographer
+ Video Editor
+ Web Developer
+ Social Media
+ Motion Graphics Artist
+ Drone Operator
+ Graphic Designer
+ Producer/Writer
+ Translator (Spanish)

_When a box is checked, proficiency rating select/input appears for each role selected. (Beginner, Intermediate, Expert)_

Label: (at least one is required)
**Please select any equipment listed that you plan to bring:**

Example placeholder or helper text: 
> Canon C100 Camcorder with 24-105mm lens, or Nikon D750 DSLR video capabilities with lens, or DJI Ronin Drone with gimbal and GoPro Hero 5 Camera, Cinevate 26” Slider, Movi M5 Steadicam, Zoom H4N, MacBook Pro 15in with Adobe Premiere)

Checkboxes: 

- 	Camcorder/video camera for video
- 	Camera for photo
- 	DSLR or mirrorless camera
- 	Mountable action camera
- 	Audio Tech recorder / microphone operator
- 	Drone
- 	Lenses
- 	Support (tripods, steadicams and sliders)
- 	Editing device (both computer and program)

_When a box is checked, a short answer titled BRAND/MODEL appears up next to the checkbox_

Label:
**Please provide at least one link to an online portfolio:**

Placeholder or helper text example: 
> vimeo.com/username  or behance.net/username or youtube.com/username

Disclaimer:

> Missions.Me is not responsible for any lost, stolen or broken equipment brought on your missions trip.

Check box: I Agree. (required)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/23/17 - 03/23/17
Work session total: 0:37:33
Grand total: 0:37:33

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/30/17 - 03/30/17
Work session total: 2:01:41
Grand total: 2:39:14

**Comment by nkeena** [comment]
> I like the design of the form overall except
Every time I select a role, the Proficiency radio buttons appear and shift all the roles, some of them even switch sides.  Not very smooth.  Also, there is lots of space in between the roles.
>I love the design of the credentials when finished.  Info displayed very well.

>This statement was left out at the bottom: 
*Missions.Me requires that Media Professionals provide their own equipment.  Rental equipment will not be provided.

>One other issue:  Proficiency for each role should be required. It currently is not.
> -Matt

<img width="1128" alt="screen shot 2017-04-03 at 3 04 54 pm" src="https://cloud.githubusercontent.com/assets/4267904/24802827/527ff738-1b77-11e7-85a2-2c5229aeb545.png">

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/07/17 - 04/07/17
Work session total: 1:10:51
Grand total: 3:50:05

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/08/17 - 04/08/17
Work session total: 0:36:46
Grand total: 4:26:51

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/10/17 - 04/10/17
Work session total: 0:18:45
Grand total: 4:45:36

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/11/17 - 04/11/17
Work session total: 0:07:31
Grand total: 4:53:07
