### ISSUE TITLE
Medical Professional Credentials

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#327]
As a user, I want to complete a questionnaire form to satisfy the travel requirement by providing proof of my qualifications and credentials as a medical professional.

**Comment by nkeena** [comment]
Initial thoughts and feedback:

Can you identify any pain points with the current process?
> 1. Current pain points that I can think of is that the requirement is showing up twice on medical missionaries' profiles. Also, if there is a way to eliminate the credentials requirement for non-medical roles (non-certified and prayer team members), that would be great. That's been a point of confusion for the majority of the missionaries signed up in those roles.

Is the current list of “I am certified to” still valid? Do we want to add or remove any?
> 2. The only other role I can think of is chiropractic. Granted, that is a role that is more rare and isn't guaranteed in every clinic.

Is the current list of “I am willing to participate in…” still valid? Do we want to add or remove anything?
> 3. Is the second "Registration" option asking if people want to help register patients or help with crowd control and line flow? If it's for the latter, that could probably be specified more clearly, just so it's not redundant to the first registration option.

Do we need the option to allow users to add “un-listed” certifications?
> 4. Yes; lots of people have knowledge and experience in things like dermatology, massage therapy, pediatric specialities, allergists, and other areas that we may not have a specific role for, but their expertise come in handy. For example, this past clinic we ran in July, we had a girl on the team who is a radiology technician; even though we don't offer those services, a man came into the clinic with a packet of x-ray and CAT scan pictures. He said he didn't understand what they meant and the medication his doctor prescribed only made him feel worse due to an incorrect diagnosis. Because we knew she had those skills, we were able to introduce her to him and from there, she was able to properly read the x-rays and scans and diagnose his condition.

Do users need the option to upload multiple files as proof of credentials?
> 5. Yes. Nicaragua is a beast for the credentials they need, specifically the ones needed for doctors, so the ability to upload multiple files will be very helpful, not just for this trip, but for future ones as well.

Do you have any other suggestions or requirements for this feature?
> 6. On the new website, I remember there's the ability for the user to see that their passport is expired on their account - is there a way to do that for medical credentials? Also, would it be possible to add a place where medical students can note how far along they are in their clinical experience for school? This year, I'm running into quite a few students who have no clinical experience (this trip would essentially be their first time working directly with patients) and it would be helpful to know that information up front so their clinic directors can know where to best place them.

**Comment by nkeena** [comment]
Required lists:

**(only certified roles) Certification checkboxes:**

- collect and review patient medical and family histories
- take blood pressure readings and record vital signs
- take blood glucose readings
- give injections
- distribute eyeglasses
- distribute pharmaceuticals
- assist in the dental clinic
- conduct dental cleanings
- run dental sterilization
- educate on hygiene and diet
- professional counseling / psychology
- chiropractic care
- massage therapy
- x-ray tech
- dermatology
- pediatrics
- [ write in other ]

**(all roles) Participation checkboxes:**

- register patients by going over their chief concern and record medical and family histories
- patient processing and clinic flow
- dental sterilization
- dental assisting
- patient education
- pharmacy assistant
- eyeglass clinic

**(Students Only)**

- note from professor
- clinic experience (yes or no)
- specializations?

**Expiration tracking**
- input fields for expiration dates on certification documents

**Comment by nkeena** [comment]
Here's an example of how we envision the conditional form working:

![medical_credentials](https://cloud.githubusercontent.com/assets/4267904/24251065/49e5e58e-0faf-11e7-9647-7ab75fc0c0da.png)

**Comment by nkeena** [comment]
I created an endpoint for this: `/api/credentials/medical`

These fields are required for `$_POST` requests:

```php
            'holder_id' => 'required|string',
            'holder_type' => 'required|in:users,reservations',
            'applicant_name' => 'required|string|max:255',
            'content' => 'required|array',
            'expired_at' => 'timestamp'
```

`$_PUT` requests:

```php
                'holder_id' => 'sometimes|required|string',
                'holder_type' => 'sometimes|required|in:users,reservations',
                'applicant_name' => 'sometimes|required|string|max:255',
                'content' => 'sometimes|required|array',
                'expired_at' => 'timestamp'
```

Be sure to run `php artisan migrate` to get the new `credentials` table.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/26/17 - 03/27/17
Work session total: 0:05:37
Grand total: 0:05:37

**Comment by giovanniorigins** [comment]
@nkeena Getting this error when post or put
![image](https://cloud.githubusercontent.com/assets/1894949/24351929/a69f519e-12b5-11e7-8c60-cd2c3b308f72.png)
Here's the stack trace
![image](https://cloud.githubusercontent.com/assets/1894949/24352058/1216a224-12b6-11e7-9a6d-76e049a6853c.png)
What exactly is `expired_at` for, when it can be set on individual certification uploads?
![image](https://cloud.githubusercontent.com/assets/1894949/24352020/e65792ce-12b5-11e7-8e39-aaaaaa6edc46.png)

**Comment by nkeena** [comment]
I used an invalid validation method. There is no such thing as `timestamp` validation. It should be `date`. I'll fix that and push with my additional changes

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/27/17 - 03/27/17
Work session total: 8:44:53
Grand total: 8:50:30

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/28/17 - 03/28/17
Work session total: 0:22:33
Grand total: 9:13:03

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/29/17 - 03/30/17
Work session total: 4:31:26
Grand total: 13:44:29

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/30/17 - 03/30/17
Work session total: 5:54:22
Grand total: 19:38:51

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/31/17 - 03/31/17
Work session total: 0:10:23
Grand total: 19:49:14

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/03/17 - 04/03/17
Work session total: 0:00:04
Grand total: 19:49:18

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/07/17 - 04/07/17
Work session total: 0:06:50
Grand total: 19:56:08
