### ISSUE TITLE
Signup form validation errors

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#328]
The birthday field on the signup form does not highlight red when left blank. It is a required field.

**Comment by nkeena** [comment]
Showing error messages below each field might be more user-friendly.

**Comment by nkeena** [comment]
**Gender needs to be a required field on the signup form.**

Because it's required in user settings, not providing it at signup is causing some confusion/issues.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:00:58
Grand total: 0:00:58

**Comment by nkeena** [comment]
The birthday inputs and gender radio inputs do not appear to indicate a validation error (no red highlighting). Was this supposed to be corrected in PR #350?

![screen shot 2017-03-13 at 3 18 51 pm](https://cloud.githubusercontent.com/assets/4267904/23871361/6aeb4aaa-0800-11e7-911e-ac374fcebdda.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/13/17 - 03/13/17
Work session total: 0:32:46
Grand total: 0:33:44

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/14/17 - 03/14/17
Work session total: 2:55:54
Grand total: 3:29:38
