### ISSUE TITLE
My profile button link in settings not updating with new profile slug

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#330]
When a user changes their profile url the event occurs asynchronously with the API, but the "my profile" button is not rendered by the html and therefore doesn't get updated until the page refreshes.

I foresee this causing confusion. Can we include that button into the settings component or make it it's own and communicate to it? Whichever solution is simplest and fastest.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:19:38
Grand total: 0:19:38

**Comment by nkeena** [comment]
This doesn't seem to be working. Has these been tested?

**Comment by giovanniorigins** [comment]
Oh yea I forgot to mention this, it seems that a response is returned from the API before the url change is confirmed. if you change it and check the URL response, you'l see that it returns the previous URL value, after a refresh or another send the new one is available.
