### ISSUE TITLE
Story input fields should clear on cancel button

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#332]
When writing a story, if user decides to cancel, the form should clear. Instead, the form still has the user's input even though it has not been published.

Some users have been confused by this.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:10:17
Grand total: 0:10:17
