### ISSUE TITLE
Include Group's Records checkbox showing for non-facilitators

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#336]
The include group's records checkbox should only appear if the authenticated user is a trip facilitator or group manager.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:09:35
Grand total: 0:09:35

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/12/17 - 03/12/17
Work session total: 0:58:14
Grand total: 1:07:49
