### ISSUE TITLE
Modals should not close on enter keystroke

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#337]
We have several modal windows throughout the site. Several users have been pressing the enter key when using the `v-select` multi-select component thinking it will close the select but instead it closes the whole modal.

Is there a way to prevent the enter key from closing the modal?

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:34:22
Grand total: 0:34:22
