### ISSUE TITLE
No matter how wide the screen there's a blank spot where a box should go

### ISSUE THREAD

**Issue by zechnelson** [missions-me/missions#343]
![img_0033](https://cloud.githubusercontent.com/assets/2917540/23815930/02a33664-05b8-11e7-950c-84de8377c313.JPG)

**Comment by nkeena** [comment]
@zechnelson Is this fixed?

**Comment by giovanniorigins** [comment]
This is a safari specific issue i think. It rounds up percentages with decimals to the nearest whole number. I don't believe there is a fix for that.
