### ISSUE TITLE
Fix error popup placing on mobile

### ISSUE THREAD

**Issue by zechnelson** [missions-me/missions#344]
Seems like they must be set to absolute and they're stuck to the top-right. Which may have a spacing that just needs to be reduced for mobile to something like 5px (just guessing).
![unnamed](https://cloud.githubusercontent.com/assets/2917540/23816042/a3e4676e-05b8-11e7-89b7-ee2d9994427e.png)

**Comment by zechnelson** [comment]
<img width="398" alt="screen shot 2017-03-11 at 10 13 40 pm" src="https://cloud.githubusercontent.com/assets/2917540/23828692/05d7be7c-06a8-11e7-98a7-5deb221e410a.png">

**Comment by nkeena** [comment]
Still getting cut off when testing with iOS simulator. I will try again on an actual device.

![simulator screen shot mar 12 2017 10 53 14 am](https://cloud.githubusercontent.com/assets/4267904/23832762/1618d54a-0712-11e7-9f7e-a4d150c07349.png)

**Comment by nkeena** [comment]
Corrected the issue by changing the alert width from 400px to 350px

![simulator screen shot mar 12 2017 2 17 02 pm](https://cloud.githubusercontent.com/assets/4267904/23834551/ac756294-072e-11e7-8515-55f77bf00157.png)
