### ISSUE TITLE
Reservation Avatar Not Displaying

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#348]
Seem to be having some issues with the reservation avatar. If the reservation email matches the authenticated user's email, it should automatically add the user's avatar.

It doesn't seem to be loading until a refresh is done. The same seems to happen when uploading a new photo - showing a broken/missing image until page is refreshed.

<img width="1000" alt="screen shot 2017-03-10 at 3 08 24 pm" src="https://cloud.githubusercontent.com/assets/4267904/23818582/8b87587c-05ca-11e7-959e-c200c9691eed.png">

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:53:35
Grand total: 0:53:35
