### ISSUE TITLE
Reservation Avatar Cropping Overlap

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#349]
Please note in the screenshot that the current size value is too long and should probably be rounded to the nearest whole number.

Also, on smaller screens or when large images are displayed to be cropped, the contact details are over lapping and making it more difficult for the user to crop the image.

<img width="957" alt="screen shot 2017-03-10 at 3 08 42 pm" src="https://cloud.githubusercontent.com/assets/4267904/23818605/b9611b0c-05ca-11e7-9444-c0ddfdbc72aa.png">

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/11/17 - 03/11/17
Work session total: 0:11:33
Grand total: 0:11:33

**Comment by zechnelson** [comment]
<img width="464" alt="screen shot 2017-03-11 at 10 34 57 pm" src="https://cloud.githubusercontent.com/assets/2917540/23828792/fb9f9850-06aa-11e7-879e-73ec146ea49b.png">

**Comment by nkeena** [comment]
<img width="819" alt="screen shot 2017-03-12 at 10 34 05 am" src="https://cloud.githubusercontent.com/assets/4267904/23832737/9165d19a-0711-11e7-856f-362d2775b431.png">

**Comment by nkeena** [comment]
Anyway to have the upload component "well" expand to full width and move the contact info down when the upload button is clicked?

**Comment by giovanniorigins** [comment]
yea, i little javascript class switching should do the trick

**Comment by nkeena** [comment]
I went ahead and moved the upload tool into it's own row

<img width="1213" alt="screen shot 2017-03-12 at 2 59 59 pm" src="https://cloud.githubusercontent.com/assets/4267904/23834906/913c3fd8-0734-11e7-9702-17b0fd830c59.png">

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/12/17 - 03/12/17
Work session total: 0:08:46
Grand total: 0:20:19

**Comment by zechnelson** [comment]
Where is this file? I would like to add space above that button so the cropping window isn't touching it.
