### ISSUE TITLE
Miami Travel Itineraries

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#355]
As a user, I want to enter my travel details to and from Miami to satisfy the travel requirement on my reservation.

**Comment by nkeena** [comment]
### Feedback

**Questions:**

- What are the pain points with the current form?
- Any special requests or scenarios that have come up that the current form has been unable to address?
- Should this form ask about other forms of transportation, and if so, why? (i.e. bus, vehicle, boat, etc.)
- What are the absolute essential details we need collected about someone’s transportation details?
- Are there any additional thoughts or ideas you have?

---
**Responses:**

>In the past  people will fly in but drive back and that is not a current option. Also flights into FLL, you may want to add the option for the train information.

>In regards to the domestic travel itinerary requirement,
-With the current form, it is hard to read the flight information when it also includes a connecting flight. I don't like how the information is separated by boxes. 
-The only special requests that I have come across are for missionaries that would like to extend their stay in country. Having an easy way to denote that on the admin side would be helpful such as being able to highlight an icon that would also show up on the missionary account that is staying longer. 
-For people within 5 hours of trip HQ, having other options like bus or taxi for other forms of transportation would be helpful. Giving them other options besides driving themselves can also alleviate the cost of parking in a lot for the duration of the trip. 
-Essential travel details would be: arrival and departure times, method of transportation, name of company (i.e Delta, Greyhound), and reservation/flight number.

>Starting at the top:
>
>This may be a good place to incorporate the Eastern/Western/Intl designation again bc its so important.  Can we add that along with little “i” buttons that reveal the same information on those three options as used on the Arrival Designation requirement?   If so, I'm open to combining them.  The reason I’m suggesting this is because that designation shapes your entire flight booking so we want to over emphasize those guidelines.
>
>IDEALLY: when you input a time that does not align with the restrictions of your Arrival Designation, you will get a warning of some kind.  This is in an ideal world obv.  I think its def something to dream of in the upcoming years.
>
>My Destination Trip HQ is:  
>	Dropdown: 	Miami International Airport (MIA) (for all full week trips)
>				Managua International Airport (MGA) (only for full week international trips)
>
>How are you getting to your Trip HQ: 
>	Dropdown: 	Flying
>				Driving from 3+ hours away
>				Coming from home (I live in the area) 
>
>	If flying, new question: I will need shuttle service from MIA to the Miami Airport Marriott Campus  RADIO: Yes or No
>				If yes: Select the date and time of your requested shuttle service.
>		(This will help us distinguish who is coming in early and who has booked their flight wrong)
>
>Design of form: Departing, Connecting and Arriving Flight need to be grouped in some way to distinguish that they are the same “itinerary” that brings you from home to MIA.  Listing RETURNING FLIGHT right after in the same font makes those drastically different items bleed together.  Maybe put a gray box around them?  Or list by LEG under INCOMING ITINERARY (from your home to MIA): LEG 1, LEG 2, LEG 3.   Then returning flight can be OUTGOING ITINERARY (MIA back to your home). 
>
>Over communicate on each section. 

>For things to add, would there be a way to alert users that they are responsible for their own hotel arrangements if they arrive earlier or stay longer at trip HQ? I know it's mentioned in the launch guides and various places on the website, but I've had quite a few missionaries assume that MM is responsible for all hotel booking, no matter when they fly in, and have been a little disappointed to find out otherwise, even after I gave them all the details for what times to book their flights.

>Bouncing off of what Taja said, I think it would be money to add and option under returning flight/outgoing itinerary.
>
>My Return Plans:
>	Dropdown: 	I am flying back to MIA with the team then immediately back home.
>				I am flying back to MIA with the team then staying in Miami for time after the trip.
>				I am staying in Nicaragua after the trip.

>I totally agree with all of this, as I've also had several missionaries who thought we were responsible for all hotel booking.
>
>I've had a handful of international missionaries who purposely didn't fill out the domestic itinerary because they are not domestic. I explained that I still needed their flight information and everything. 
>
>The way that the 4 boxes are now, I finally understand the order it's supposed to go in. However, if there was a small key to the side of the page explaining it. 
>
>When you input the information, it just seems a bit overwhelming. Maybe breaking it up into two columns, with the first three on one side and the second labeled "After Nicaragua" or something. Maybe using a number system or something.
>
>Getting to Miami
>Departing (from your hometown) 
>Connecting flight (if you have one)
>Arriving (in Miami) 
>
>Going Home
> Returning (to your hometown, from Miami)
>
>Obviously, you can use better word choices there, but I've just had so many people trying to figure it out and it just seems too much for them. If you do use a number system or columns or something like that, maybe you could keep that organization on there once it's already put into the system. That way, they can still see it the same way when it's submitted.

**Comment by nkeena** [comment]
I think we can simplify it to something like this:


ARRIVE IN MIAMI

Airline:
Flight No.:
Airport:
Arrival Time:
Arrival Date:

Do you have a prior connecting flight? [yes] or [no]

(if yes:)

Airline:
Flight No.:


RETURN HOME

Airline:
Flight No.:
Airport:
Departure Time:
Departure Date:

**Comment by nkeena** [comment]
@giovanniorigins Can you start mocking the form detailed above? The form will be conditionally displayed based on the travel method selected for arrival and return.

This does not need it's own record page. This component should be embedded in `document-manager` like the `arrival-designation` and `airport-preference` components are.

I haven't written the Itinerary API yet so it's subject to change but here's what it might look like for a single entry or item in the Itinerary (two would be needed "arrival" and "return")

```php
'itinerant_id' => 'required|string', (i.e. reservation id)
'itinerant_type' => 'required|string', (i.e. "reservations")
'item' => 'required|string', (i.e "Arrive in Miami")
'date_time' => 'timestamp',
'location' => [
    'name' => 'required|string',
    'address' => 'string',
    'city' => 'string',
    'state' => 'string',
    'country_code' => 'string',
    'phone' => 'string',
    'fax' => 'string',
    'email' => 'string',
    'website' => 'string'
],
'transport' => [
    'type' => 'required|string|in:flight,bus,vehicle,train',
    'vessel_no' => 'required|string',
    'name' => 'required|string',
    'call_sign' => 'string',
    'domestic' => 'boolean',
    'capacity' => 'numeric',
    'campaign_id' => 'required|exists:campaigns,id',
]
```

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/04/17 - 04/04/17
Work session total: 0:28:46
Grand total: 0:28:46

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/06/17 - 04/06/17
Work session total: 0:22:49
Grand total: 0:51:35

**Comment by giovanniorigins** [comment]
http://iatacodes.org/

**Comment by giovanniorigins** [comment]
fb8189a628698a2d2ac5aa74423f45a4157a3d8b

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/07/17 - 04/07/17
Work session total: 2:22:14
Grand total: 3:13:49

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/12/17 - 04/12/17
Work session total: 0:48:00
Grand total: 4:01:49

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/19/17 - 04/19/17
Work session total: 5:27:00
Grand total: 9:28:49

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/20/17 - 04/20/17
Work session total: 6:07:23
Grand total: 15:36:12

**Comment by nkeena** [comment]
Perhaps the component can have two identical form sections which would represent the two items.

Here is how inputs could be matched to the API:


#### arrival
Travel Method [select] -> `transport.type`

(if flight)
Airline: [select] -> `transport.name`
Flight No. [text input] -> `transport.vessel_no`

Airport [text input] -> `hub.name`
IATA [hidden] -> `hub.call_sign`
city [hidden] -> `hub.city`
country [hidden] -> `hub.country`

Arrival Date & Time [date time picker] -> `activity.occurred_at`

#### another item (possibly the 3rd)
Do you have a prior connecting flight? [yes] or [no]

#### return home item
like above

**Comment by nkeena** [comment]
Validation rules:

```json
        return [
            'reservation_id' => 'required|exists:reservations,id',
            'items' => 'required|array',
            'items.*.transport' => 'required|array',
            'items.*.transport.type' => 'required|string|in:flight,bus,vehicle,train',
            'items.*.transport.vessel_no' => 'required|string',
            'items.*.transport.name' => 'required|string',
            'items.*.transport.call_sign' => 'string',
            'items.*.transport.domestic' => 'boolean',
            'items.*.transport.capacity' => 'numeric',
            'items.*.activity' => 'required|array',
            'items.*.activity.name' => 'required|string|max:100',
            'items.*.activity.description' => 'string|max:200',
            'items.*.activity.occurred_at' => 'required|date',
            'items.*.hub' => 'required|array',
            'items.*.hub.name' => 'required|string',
            'items.*.hub.call_sign' => 'required|string',
            'items.*.hub.address' => 'string',
            'items.*.hub.city' => 'required|string',
            'items.*.hub.state' => 'string',
            'items.*.hub.zip' => 'string',
            'items.*.hub.country' => 'required|string'
        ];
```

**Comment by nkeena** [comment]
`call_sign` for a flight = IATA code

Anything else falls into these categories:

`BUS` = buses
`TRN` = Train
`CAR` = vehicle

**Comment by nkeena** [comment]
Example itinerary lookup with activities, hubs, and transports included:

```json
{
    "data": {
        "id": "8850333f-7cc2-4509-b6db-33c8d3e7642c",
        "name": "Edmund Jessy Wolff's Travel Itinerary",
        "curator_id": "0005a7ea-f92f-371e-878a-d28423ea2cfb",
        "curator_type": "reservations",
        "activities": {
            "data": [
                {
                    "id": "bd0f3041-aebb-49aa-a66a-ddda26da9952",
                    "name": "Arrive in Miami",
                    "description": null,
                    "participant_id": "0005a7ea-f92f-371e-878a-d28423ea2cfb",
                    "participant_type": "reservations",
                    "occurred_at": "2017-07-21 15:45:00",
                    "created_at": "2017-04-21 18:14:34",
                    "updated_at": "2017-04-21 18:14:34",
                    "deleted_at": null,
                    "hubs": {
                        "data": [
                            {
                                "id": "0d5463b0-6067-4432-bb7c-6d4e8a94ad6f",
                                "campaign_id": "b304fd5a-3c18-4a77-9722-e6138f3429d7",
                                "name": "Miami International Airport",
                                "call_sign": null,
                                "address": null,
                                "city": "Miami",
                                "state": null,
                                "zip": null,
                                "country_code": null,
                                "created_at": "2017-04-21 18:14:34",
                                "updated_at": "2017-04-21 18:14:34"
                            }
                        ]
                    },
                    "transports": {
                        "data": [
                            {
                                "id": "b8d20208-8f44-470f-a05c-ef26fd299a2f",
                                "campaign_id": "b304fd5a-3c18-4a77-9722-e6138f3429d7",
                                "type": "flight",
                                "vessel_no": "DL100",
                                "name": "Delta Airlines",
                                "domestic": true,
                                "capacity": 9999,
                                "call_sign": null,
                                "created_at": "2017-04-21 18:14:34",
                                "updated_at": "2017-04-21 18:14:34",
                                "links": [
                                    {
                                        "rel": "self",
                                        "uri": "/api/transports/b8d20208-8f44-470f-a05c-ef26fd299a2f"
                                    }
                                ]
                            }
                        ]
                    }
                },
                {
                    "id": "97b10296-c983-43cb-bb69-b321fee23845",
                    "name": "Depart Miami",
                    "description": null,
                    "participant_id": "0005a7ea-f92f-371e-878a-d28423ea2cfb",
                    "participant_type": "reservations",
                    "occurred_at": "2017-07-29 08:30:00",
                    "created_at": "2017-04-21 18:14:34",
                    "updated_at": "2017-04-21 18:14:34",
                    "deleted_at": null,
                    "hubs": {
                        "data": [
                            {
                                "id": "dd3dfe88-ed7c-4890-bcc2-97f27585337a",
                                "campaign_id": "b304fd5a-3c18-4a77-9722-e6138f3429d7",
                                "name": "Miami International Airport",
                                "call_sign": null,
                                "address": null,
                                "city": "Miami",
                                "state": null,
                                "zip": null,
                                "country_code": null,
                                "created_at": "2017-04-21 18:14:34",
                                "updated_at": "2017-04-21 18:14:34"
                            }
                        ]
                    },
                    "transports": {
                        "data": [
                            {
                                "id": "57a8af30-207f-4806-a4ba-5af52cf70f0e",
                                "campaign_id": "b304fd5a-3c18-4a77-9722-e6138f3429d7",
                                "type": "flight",
                                "vessel_no": "DL200",
                                "name": "Delta Airlines",
                                "domestic": true,
                                "capacity": 9999,
                                "call_sign": null,
                                "created_at": "2017-04-21 18:14:34",
                                "updated_at": "2017-04-21 18:14:34",
                                "links": [
                                    {
                                        "rel": "self",
                                        "uri": "/api/transports/57a8af30-207f-4806-a4ba-5af52cf70f0e"
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        "updated_at": "2017-04-21 18:14:34",
        "created_at": "2017-04-21 18:14:34",
        "deleted_at": null,
        "links": [
            {
                "rel": "self",
                "uri": "/api/itineraries/8850333f-7cc2-4509-b6db-33c8d3e7642c"
            }
        ]
    }
}
```

**Comment by nkeena** [comment]
Here are the individual endpoints if you need them:

Activities: `http://missions.dev/api/activities/{id}` (Full CRUD)

Sample response:
```json
{
    "data": {
        "id": "bd0f3041-aebb-49aa-a66a-ddda26da9952",
        "name": "Arrive in Miami",
        "description": null,
        "participant_id": "0005a7ea-f92f-371e-878a-d28423ea2cfb",
        "participant_type": "reservations",
        "occurred_at": "2017-07-21 15:45:00",
        "created_at": "2017-04-21 18:14:34",
        "updated_at": "2017-04-21 18:14:34",
        "deleted_at": null
    }
}
```

Hubs: `http://missions.dev/api/hubs/{id}` (full CRUD)

Sample Response:

```json
{
    "data": {
        "id": "0d5463b0-6067-4432-bb7c-6d4e8a94ad6f",
        "campaign_id": "b304fd5a-3c18-4a77-9722-e6138f3429d7",
        "name": "Miami International Airport",
        "call_sign": null,
        "address": null,
        "city": "Miami",
        "state": null,
        "zip": null,
        "country_code": null,
        "created_at": "2017-04-21 18:14:34",
        "updated_at": "2017-04-21 18:14:34"
    }
}
```

Transports: `http://missions.dev/api/transports/{id}` (full CRUD)

Sample Response:

```json
{
    "data": {
        "id": "b8d20208-8f44-470f-a05c-ef26fd299a2f",
        "campaign_id": "b304fd5a-3c18-4a77-9722-e6138f3429d7",
        "type": "flight",
        "vessel_no": "DL100",
        "name": "Delta Airlines",
        "domestic": true,
        "capacity": 9999,
        "call_sign": null,
        "created_at": "2017-04-21 18:14:34",
        "updated_at": "2017-04-21 18:14:34",
        "links": [
            {
                "rel": "self",
                "uri": "/api/transports/b8d20208-8f44-470f-a05c-ef26fd299a2f"
            }
        ]
    }
}
```

**Comment by nkeena** [comment]
If you need to attach or detach a hub or transport from an activity (I don't imagine this would be necessary with the travel itinerary component) then use these endpoints:

Transport Activities: 
`http://missions.dev/api/transports/{transportId}/activities/{activityId}` (CRD)

Hub Activities: 
`http://missions.dev/api/transports/{transportId}/hubs/{hubId}` (CRD)

Just pass an array of activity ids called `activities` to the POST or DELETE methods on these endpoints to add or remove activities.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/24/17 - 04/24/17
Work session total: 4:18:05
Grand total: 25:12:36

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/25/17 - 04/25/17
Work session total: 3:06:08
Grand total: 28:18:44

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/01/17 - 05/01/17
Work session total: 0:59:36
Grand total: 29:18:20
