### ISSUE TITLE
Use a referral Code (RecruitOne)

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#356]
As a user, I want to use a referral code when I register for a trip so I can get an instant credit toward my trip.

**Comment by nkeena** [comment]
Check if code is valid with `PUT` request to `trips/{id}/promo` with payload `{promocode: PROMO-CODE}`. 

If invalid it will return a `422` error with message. If valid it will return a dollar amount `"100.00"`

This amount should be added to the cost list as a `Promotional Credit` and deduct from the final amount.

`promocode` should be sent to `trips/{id}/register` as well so the API can issue the credit behind the scenes after registration is completed.

*Important:* this does not remove the required deposit! This is simply an additional credit that is being issued.

**Comment by nkeena** [comment]
The feature branch: https://github.com/missions-me/missions/tree/feature-referral-codes

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/12/17 - 04/12/17
Work session total: 0:12:12
Grand total: 0:12:12
