### ISSUE TITLE
Group search and pagination not working

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#360]
Search and pagination do not appear to be working on the `groups.vue` component found under "Groups Partnered with us" on the `/groups` page.

Not seeing any errors in the console either. :/

**Comment by giovanniorigins** [comment]
will take a look now

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/14/17 - 03/14/17
Work session total: 0:30:00
Grand total: 0:30:00
