### ISSUE TITLE
Admin Reservation Trip Rep Filter not populating all reps

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#366]
It seems that the rep filter only populates reps from whichever reservations are being returned from the API. We need to figure out a way to display all reps in the system. Maybe a new endpoint is needed?

**Comment by nkeena** [comment]
Any thoughts on this one @giovanniorigins ?

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/14/17 - 03/14/17
Work session total: 0:07:56
Grand total: 0:07:56

**Comment by giovanniorigins** [comment]
How about something like this?
```
/**
     * By facilitating.
     *
     * @param $url
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function isFacilitator($isFacilitator)
    {
        if( !$isFacilitator ) return $this;

        return $this->has('facilitating', '>', 1)->orWhereHas('managing', function ($managing) {
            $managing->has('trips', '>', 1);
        });
    }
```

**Comment by nkeena** [comment]
Reps are different than facilitators.

You can see live results from
