### ISSUE TITLE
Trip Duplication not working

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#373]
Click duplicate button ... then a bunch of payment objects kept populating the console.

I think this feature is out of date with changes that have been made. Might require a deep dive.

**Comment by nkeena** [comment]
I disabled duplication for now: fb3dde8499dc76c6fcd8a0213f81095f916f46db

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/14/17 - 03/14/17
Work session total: 0:12:24
Grand total: 0:12:24
