### ISSUE TITLE
Reservation edit form not populating some fields

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#379]
Appears to only be shirt size. relationship status, and gender. I think it might be a case-sensitive issue.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/15/17 - 03/15/17
Work session total: 0:11:28
Grand total: 0:11:28
