### ISSUE TITLE
Impersonated user data not clearing

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#387]
When you stop impersonating a user, the data seems to hang around. It won't update either. When you go to impersonate another user, the old impersonated user is still populating the dom.

![screen shot 2017-03-16 at 5 07 31 pm](https://cloud.githubusercontent.com/assets/4267904/24018710/6fe8bb1a-0a6b-11e7-8ac9-251cb6a50c5f.png)

![screen shot 2017-03-16 at 5 07 41 pm](https://cloud.githubusercontent.com/assets/4267904/24018715/73a2a900-0a6b-11e7-82af-ca74bbe0d7a4.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/16/17 - 03/16/17
Work session total: 1:07:05
Grand total: 1:07:05
