### ISSUE TITLE
Possible malformed GET request being generated /dashboard/reservations/cf61f137-acfd-4610-90c5-8d6fb0c8b6cc/[object%20Object]

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#396]
## Error in app-one

**InvalidArgumentException** in **GET /dashboard/reservations/cf61f137-acfd-4610-90c5-8d6fb0c8b6cc/[object%20Object]**
View [dashboard.reservations.[object Object]] not found.

[View on Bugsnag](https://app.bugsnag.com/missions-dot-me/app-one/errors/58af25c76293db499f021620?event_id=58c96bfd6881e21100b51424)

## Stacktrace

    app/Http/Controllers/Web/Dashboard/ReservationsController.php:31 - App\Http\Controllers\Web\Dashboard\ReservationsController::show
    app/Http/Middleware/Authenticate.php:28 - App\Http\Middleware\Authenticate::handle
    app/Http/Middleware/Impersonate.php:24 - App\Http\Middleware\Impersonate::handle

[View full stacktrace](https://app.bugsnag.com/missions-dot-me/app-one/errors/58af25c76293db499f021620?event_id=58c96bfd6881e21100b51424)

**Comment by nkeena** [comment]
@giovanniorigins not sure if this is still an issue. Last occurrence was yesterday before the update to registration wizard for no-deposit trips. I'd like to be sure though.

It seems to me that something went wrong during the registration process and instead of redirecting to `dashboard/reservations/{id}/details`, it passed an object to the last part of the URL.

**Comment by giovanniorigins** [comment]
I've been trying to trace this, but no luck. It might be tied to impersonation, based on the stacktrace so I'll try that too.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/19/17 - 03/20/17
Work session total: 0:12:41
Grand total: 0:12:41

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/20/17 - 03/20/17
Work session total: 0:38:03
Grand total: 0:50:44

**Comment by nkeena** [comment]
An error linked to this issue has been reopened in Bugsnag
[**InvalidArgumentException** in **GET /dashboard/reservations/3f538efb-2183-4f41-b654-f8b802978c2c/[object%20Object]**](https://app.bugsnag.com/missions-dot-me/app-one/errors/58af25c76293db499f021620?event_id=58f01a9985d609001802815a&i=gh&m=ra)

**Comment by nkeena** [comment]
An error linked to this issue has been reopened in Bugsnag
[**InvalidArgumentException** in **GET /dashboard/reservations/5a644390-2e75-4b42-90df-29f2ce24df03/[object%20Object]**](https://app.bugsnag.com/missions-dot-me/app-one/errors/58af25c76293db499f021620?event_id=58f6bc0c5bf1c70018448339&i=gh&m=ra)

**Comment by nkeena** [comment]
An error linked to this issue has been reopened in Bugsnag
[**InvalidArgumentException** in **GET /dashboard/reservations/0f1dbcc5-99ae-4b6d-b3fa-6092f76cedc3/[object%20Object]**](https://app.bugsnag.com/missions-dot-me/app-one/errors/58af25c76293db499f021620?event_id=592d6f5bd8d9d70018c14296&i=gh&m=ra)

**Comment by nkeena** [comment]
An error linked to this issue has been reopened in Bugsnag
[**InvalidArgumentException** in **GET /dashboard/reservations/82ac4f84-03ae-43e0-a050-ef23599b6085/[object%20Object]**](https://app.bugsnag.com/missions-dot-me/app-one/errors/58af25c76293db499f021620?event_id=5942ff04c6ce0e0017839dc9&i=gh&m=ra)
