### ISSUE TITLE
Height and widht not set on cropper - possible crop handles not showing?

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#398]
## Error in app-one

**Intervention\Image\Exception\InvalidArgumentException** in **POST /api/uploads**
Width and height of cutout needs to be defined.

[View on Bugsnag](https://app.bugsnag.com/missions-dot-me/app-one/errors/58c7ee9553dd451100a6a248?event_id=58c7eec36743771100c524f3)

## Stacktrace

    app/Http/Controllers/Api/UploadsController.php:191 - App\Http\Controllers\Api\UploadsController::process
    app/Http/Controllers/Api/UploadsController.php:74 - App\Http\Controllers\Api\UploadsController::store

[View full stacktrace](https://app.bugsnag.com/missions-dot-me/app-one/errors/58c7ee9553dd451100a6a248?event_id=58c7eec36743771100c524f3)

**Comment by nkeena** [comment]
@giovanniorigins I have noticed in some cases if I upload a pictures and before saving it, change my mind and click upload again to select a new picture, that the crop handles sometimes don't appear.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/11/17 - 04/12/17
Work session total: 6:24:53
Grand total: 6:24:53

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/12/17 - 04/12/17
Work session total: 3:59:26
Grand total: 10:24:19

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/13/17 - 04/13/17
Work session total: 0:00:02
Grand total: 10:24:21
