### ISSUE TITLE
Change number of results showing in reservation list (dashboard)

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#400]
Team Facilitators would like an option to change the number of reservations showing at one time in their dashboard. Right now it's locked in at 10. We could replicate the functionality in the admin with a drop down to select how many to show.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/19/17 - 03/19/17
Work session total: 0:37:54
Grand total: 0:37:54
