### ISSUE TITLE
Add filters to reservation list (dashboard)

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#401]
Team facilitators would like the following filters:

- by role
- by gender
- by marital status
- by applied cost
    - payment status
- by requirement
    - requirement status
- by shirt size
- by age range
- by travel companions (yes or no)

I imagine we can just copy admin filters.

**Comment by giovanniorigins** [comment]
Good thing they are there already, just needs the filter aside 😃

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/19/17 - 03/19/17
Work session total: 1:54:04
Grand total: 1:54:04
