### ISSUE TITLE
Pre-selected optional costs

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#405]
Currently, "standard" optional cost should be selected because it is being used as a way to track necessary rooming designations (i.e. double room, triple room, standard, etc.)

Some possible solutions:
1) add a flag to costs that can be used to select it by default on trip registration
2) hardcode the standard option into optional costs step (uncheck if other option is selected)

**Comment by nkeena** [comment]
New Solution: 

- [ ] convert checkboxes on trip registration form to radio inputs
- [ ] add validation to make a selection required

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/14/17 - 04/14/17
Work session total: 5:31:48
Grand total: 5:31:48
