### ISSUE TITLE
Add trips list to group details page (admin)

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#407]
Could re-use trips list component in admin, but would need to be scoped to the parent group instead of the parent campaign.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/19/17 - 03/19/17
Work session total: 0:27:02
Grand total: 0:27:02
