### ISSUE TITLE
Search term to persist in local storage for reservations list

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#410]
Admins have requested that their most recent search be remembered after they navigate away from the page.

I know a search request is initiated with every single keystroke after a certain delay; maybe saving the search request could happen after an even longer delay?

@giovanniorigins Do you see any potential problems with this request?

**Comment by giovanniorigins** [comment]
I currently don't foresee any problems with this request. What comes to mind though, is saving multiple search texts, like the last five searches that can be easily selected from a dropdown attached to the search input. Any thoughts?

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/03/17 - 04/03/17
Work session total: 2:08:20
Grand total: 2:08:20

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/04/17 - 04/04/17
Work session total: 0:00:15
Grand total: 2:08:35

**Comment by giovanniorigins** [comment]
@nkeena is this working?
