### ISSUE TITLE
Weird date string appearing in API data on trip facilitators page

### ISSUE THREAD

**Issue by giovanniorigins** [missions-me/missions#416]
@nkeena Are you seeing something like this if you view the trip data received from the API while on the trip facilitators page? Specifically the `published_at` date string
![image](https://cloud.githubusercontent.com/assets/1894949/24080430/6939e5e4-0c75-11e7-885b-aa10e1463b21.png)

**Comment by giovanniorigins** [comment]
Viewing the same data on trip edit page...
![image](https://cloud.githubusercontent.com/assets/1894949/24080441/a162f910-0c75-11e7-9346-3a9f7adc715e.png)

**Comment by giovanniorigins** [comment]
Doing more testing, I discovered that `?include=facilitators.user`, specifically the `.users` causes this problem. Must have been an old api issue.

**Comment by giovanniorigins** [comment]
It fails to add facilitators

**Comment by nkeena** [comment]
Very interesting. I have not seen this issue until now. I will take a look and see what is going on.
