### ISSUE TITLE
Filter Reservations by Trip Type

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#417]
Add option to filter reservations by trip type.

- add filter to API
- add filter to UI (admin & dashboard)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/20/17 - 03/20/17
Work session total: 1:51:30
Grand total: 1:51:30

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/21/17 - 03/21/17
Work session total: 0:00:09
Grand total: 1:51:39
