### ISSUE TITLE
Birthdays not saving correctly?

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#424]
From user:
> I just registered for Nicaragua, through our group with church, however I did see an error. On previous pages that requires basic information, my birth date is entered correctly **09-20-1984**, but once **ready to review and complete registration**, it shows my birth date as **11-03-1984**. Is there any way to correct that on your end? I would hate for there to be any issues because of this error. 

<img width="192" alt="screen shot 2017-03-21 at 10 00 50 am" src="https://cloud.githubusercontent.com/assets/4267904/24150857/6320004a-0e1d-11e7-998e-0e8a767e3561.png">

<img width="151" alt="screen shot 2017-03-21 at 10 01 22 am" src="https://cloud.githubusercontent.com/assets/4267904/24150862/64cafb98-0e1d-11e7-8ac6-a1641f92b843.png">

**Comment by giovanniorigins** [comment]
`moment().set()` has inconsistent behaviour with string and integer date parts

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/21/17 - 03/21/17
Work session total: 0:40:22
Grand total: 0:40:22
