### ISSUE TITLE
Trip Payments not transferring on duplication

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#431]
I previously disabled `syncResources` method whenever a trip is created or updated because we didn't want that process happening each time a change is made. This method is needed for trip duplication. So I started working on a new endpoint `trips/duplicate` that is a simple POST method like the `store` method but instead includes a call to this `syncResources` method.

Everything transfer as expected except for the payments. They just get duplicated in the trip we duplicated from.

<img width="872" alt="screen shot 2017-03-23 at 3 27 38 pm" src="https://cloud.githubusercontent.com/assets/4267904/24266489/46bca6e4-0fdd-11e7-8aaf-2a195dc73e23.png">

I'm not super clear on what's happing here but in `admin-trip-duplicate.vue` I think this might be the culprit. Payments need to be assigned to the new cost ids of the duplicated trip. They cannot have the same cost ids as the old trip. That might be the reason they are showing up in the old trip.

```js
// trim costs
this.trip.costs = this.trip.costs.data;
_.each(this.trip.costs, function (cost) {
   payments[cost.id] = cost.payments.data;
   delete cost.payments;
   delete cost.links;
});
```

**Comment by giovanniorigins** [comment]
@nkeena So I'm running into this problem where `$cost->createDefaultPayment();` in `API/CostsController` is creating an upfront payment before i can add a payment for the cost. 
How should I go about this? 

Is it possible to include a payments array when `POST` to `/costs` and if a payments array is not present, it creates a default cost?

**Comment by nkeena** [comment]
That's a good idea. We could do something like that. It's simple and flexible

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/23/17 - 03/23/17
Work session total: 2:31:36
Grand total: 2:31:36

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/24/17 - 03/24/17
Work session total: 0:41:33
Grand total: 3:13:09
