### ISSUE TITLE
(Admin) Traveler details don't populate when managing user is selected when creating a reservation

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#437]
Traveler details don't seem to populate when a managing user is selected. Can we have it populate the basic traveler details as default when a managing user is selected?

**Comment by nkeena** [comment]
![screen shot 2017-03-27 at 3 24 52 pm](https://cloud.githubusercontent.com/assets/4267904/24374177/e24bc726-1301-11e7-9bec-a12974ac27f1.png)

Getting an error when trying to clear user select and search a new user

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 03/27/17 - 03/27/17
Work session total: 1:15:23
Grand total: 1:15:23
