### ISSUE TITLE
Does not redirect to dashboard on login (IE only)

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#446]
There seems to be a problem where the user is not redirected to the dashboard when they login on IE browser. When the user clicks "login" nothing happens until you manually refresh the page.

I tested this on the latest version of IE on a Windows 10 machine.

**Comment by giovanniorigins** [comment]
is this microsoft edge or IE?

**Comment by nkeena** [comment]
It appears to be an issue with IE not Edge.
