### ISSUE TITLE
Can't upload Group Avatar (logo)

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#461]
Getting these errors when trying to upload a logo.

![screen shot 2017-04-06 at 11 08 54 am](https://cloud.githubusercontent.com/assets/4267904/24805476/ea4bec18-1b7f-11e7-8cd3-4165c771cb18.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/07/17 - 04/07/17
Work session total: 3:03:10
Grand total: 3:03:10

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/08/17 - 04/08/17
Work session total: 0:00:09
Grand total: 3:03:19
