### ISSUE TITLE
Search does not display values sometimes

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#463]
This happens randomly. When performing searches, it returns results but does not display them.

![screen shot 2017-04-07 at 4 20 01 pm](https://cloud.githubusercontent.com/assets/4267904/24818360/31e8dc60-1bae-11e7-88c7-f1e299aff0a6.png)

No error in the console either :/

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/08/17 - 04/08/17
Work session total: 0:55:50
Grand total: 0:55:50
