### ISSUE TITLE
Add validation to dynamic fields

### ISSUE THREAD

**Issue by giovanniorigins** [missions-me/missions#479]
there is a `field` attribute that accepts an expression

example
```
<div v-for="(i, room) in rooms">
    <input type="text" :field="'number' + i" v-validate="{ required: true }" class="form-control" placeholder="add room number">
</div>
```

**Comment by giovanniorigins** [comment]
@nkeena other than credentials forms, can you think of any other forms this needs right now?

**Comment by nkeena** [comment]
@giovanniorigins All record forms like (passports, visas, medical releases, etc.) are the highest priority right now

**Comment by giovanniorigins** [comment]
### Dynamic Validation Forms
- [ ] Media Credentials
- [ ] Medical Credentials
- [ ] Medical Releases

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/18/17 - 04/18/17
Work session total: 4:56:46
Grand total: 9:58:40

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/20/17 - 04/21/17
Work session total: 3:22:15
Grand total: 13:20:55
