### ISSUE TITLE
Admin Reservation Form won't Populate with User Data

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#497]
Getting this error in the console when I select the user's name. It also won't clear my search term after making a selection.

![screen shot 2017-04-25 at 2 51 58 pm](https://cloud.githubusercontent.com/assets/4267904/25402538/fc6c78b8-29c6-11e7-8ce4-c2edac3076d6.png)

**Comment by giovanniorigins** [comment]
the search term not clearing is a result of the error. the callback fails and terminates and js afterward

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/25/17 - 04/25/17
Work session total: 0:29:42
Grand total: 0:29:42
