### ISSUE TITLE
Travel Itinerary Requirement Form

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#504]
Getting validation error with airport where first option selected is always invalid. It is also showing invalid initially when the component loads.

<img width="734" alt="screen shot 2017-04-27 at 10 32 56 am" src="https://cloud.githubusercontent.com/assets/4267904/25488593/6b51d038-2b35-11e7-8a22-b9218cb1ed09.png">

After completing the form and saving the itinerary, the component returns no information until the page is refreshed.

<img width="826" alt="screen shot 2017-04-27 at 10 34 07 am" src="https://cloud.githubusercontent.com/assets/4267904/25488646/89ebba7c-2b35-11e7-82af-1ff628e9b2f2.png">

Having a separate button for each section feels clunky. A single "Update Itinerary" would be ideal. I will create an travel itinerary update endpoint to try and manage this mass update with a single API call.

There is also no way of indicating that you are finished making changes (going with a single update button should solve this problem), and no way to back out (i.e. cancel button).

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/27/17 - 04/27/17
Work session total: 3:04:32
Grand total: 3:04:32

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/27/17 - 04/29/17
Work session total: 2:12:02
Grand total: 5:16:34

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 04/29/17 - 04/29/17
Work session total: 0:57:07
Grand total: 6:13:41

**Comment by nkeena** [comment]
Both checkboxes are being selected when I click the top one.

<img width="753" alt="screen shot 2017-05-01 at 10 24 38 am" src="https://cloud.githubusercontent.com/assets/4267904/25582164/d087825a-2e59-11e7-82a6-b4de078a61b7.png">

**Comment by nkeena** [comment]
Need to change title from "Arrive at Training Location" to "Arrive in Destination Country" when this box is checked.

<img width="693" alt="screen shot 2017-05-01 at 10 24 55 am" src="https://cloud.githubusercontent.com/assets/4267904/25582188/e96e99a2-2e59-11e7-912e-c94860300eb7.png">

**Comment by nkeena** [comment]
When editing an itinerary, this box is checked by default? Was not selected on creation.

<img width="768" alt="screen shot 2017-05-01 at 10 32 15 am" src="https://cloud.githubusercontent.com/assets/4267904/25582221/0c053b6a-2e5a-11e7-97dd-35be3615656c.png">

**Comment by nkeena** [comment]
Activity `occurred_at` dates are displaying incorrectly (today's date). API and database are returning correct value.

<img width="230" alt="screen shot 2017-05-01 at 10 33 59 am" src="https://cloud.githubusercontent.com/assets/4267904/25582284/62d52ffe-2e5a-11e7-8e9f-deaff982cbcb.png">

**Comment by nkeena** [comment]
When changing a transportation type, transport and hub fields should clear.

<img width="751" alt="screen shot 2017-05-01 at 10 45 57 am" src="https://cloud.githubusercontent.com/assets/4267904/25582470/754a52ee-2e5b-11e7-8f5f-5907d16743af.png">

**Comment by nkeena** [comment]
When updating an itinerary, need a cancel button so no changes go into effect and also maybe a "Start Over" button to delete the itinerary completely.

**Comment by nkeena** [comment]
We should also change the language for each label within departure, connection, and return.

Arrive at Training Location
---
Arriving at Airport (flight)
Drop off location (vehicle/bus)
Arriving at Station (train)
Arriving at Date & Time

Depart from Training Location (Rename to: Return Home)
---
Depart from Airport (Flight)
Pick up Location (Vehicle/Bus)
Depart from Station (train)
Departing at Date & Time

Travel Connection _Prior to Arriving_ (add)
----
Making Connection at Airport (flight)
Connection Location (vehicle/bus)
Making Connection at Station (train)
Connection Departs at Date & Time

**Comment by nkeena** [comment]
**Outstanding Todos:**

- [ ] Scope teams to given group
- [ ] Scope teams to chosen campaign
- [ ] Add campaign chooser
- [ ] Add validation to prevent unapproved leadership roles from being added
    - Only leadership roles may be assigned as team leader / group leader
    - There is a `leadership()` method in the `TeamRole` utilities class that will only return leadership roles. I think we just need a route to it.

**Comment by nkeena** [comment]
Getting a client-slide validation error on country select:

<img width="769" alt="screen shot 2017-05-01 at 1 21 24 pm" src="https://cloud.githubusercontent.com/assets/4267904/25587233/1cca0054-2e71-11e7-8421-e84c72cf2448.png">

As per previous comment, language should change dynamically to bring more clarity.

> Need to change title from "Arrive at Training Location" to "Arrive in Destination Country" when this box is checked.

<img width="609" alt="screen shot 2017-05-01 at 1 22 45 pm" src="https://cloud.githubusercontent.com/assets/4267904/25587330/8cc0ce60-2e71-11e7-9038-2a0f0c1e3834.png">

**Comment by nkeena** [comment]
Cancel button should only be available after an itinerary has been created. 

Right now, when creating a new itinerary, the cancel button is visible and when clicked removes all inputs, preventing the user from finishing the form.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/01/17 - 05/02/17
Work session total: 4:38:40
Grand total: 10:52:21

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/02/17 - 05/02/17
Work session total: 0:45:57
Grand total: 11:38:18
