### ISSUE TITLE
TF Room Management

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#509]
As a team facilitator I want to assign team members to rooms so we can appropriately match roommates.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/02/17 - 05/02/17
Work session total: 2:25:22
Grand total: 2:25:22

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/03/17 - 05/03/17
Work session total: 2:58:44
Grand total: 5:24:06

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/04/17 - 05/04/17
Work session total: 1:51:16
Grand total: 7:15:22

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/05/17 - 05/05/17
Work session total: 1:59:38
Grand total: 9:15:00

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/08/17 - 05/08/17
Work session total: 0:00:05
Grand total: 9:15:05

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/10/17 - 05/10/17
Work session total: 5:52:19
Grand total: 15:07:24

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/11/17 - 05/11/17
Work session total: 2:22:54
Grand total: 17:30:18

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/15/17 - 05/15/17
Work session total: 1:27:25
Grand total: 18:57:43

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/22/17 - 05/22/17
Work session total: 0:56:14
Grand total: 19:53:57

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/23/17 - 05/23/17
Work session total: 1:35:07
Grand total: 21:29:04

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/30/17 - 05/30/17
Work session total: 7:09:05
Grand total: 28:38:09

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/31/17 - 05/31/17
Work session total: 2:43:59
Grand total: 31:22:08

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/10/17 - 06/10/17
Work session total: 0:45:27
Grand total: 32:07:35
