### ISSUE TITLE
Travel Itinerary let's users enter invalid Airlines

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#518]
It seems users are able to type in non-existing airline names as the value for the airline. It throws a validation error but no explanation is given to the user.

Is there a way to force users to select from the drop down? Can we have the list pre-populate without having to start typing first (like country dropdown)?

![screen shot 2017-05-03 at 12 24 43 pm](https://cloud.githubusercontent.com/assets/4267904/25671202/14496194-2ffd-11e7-93ba-3352cce1cdb3.png)

**Comment by giovanniorigins** [comment]
I think it is showing invalid because they are not able to enter an iata, once that field is visible it should work

**Comment by giovanniorigins** [comment]
Wait, that is something else it seems, nvm

**Comment by nkeena** [comment]
@giovanniorigins if you notice in the screen shot the "Delta" is not a selected item. Should look like this...

<img width="556" alt="screen shot 2017-05-03 at 12 46 19 pm" src="https://cloud.githubusercontent.com/assets/4267904/25671564/85cb0b64-2ffe-11e7-8f17-190dab7e8561.png">

**Comment by giovanniorigins** [comment]
Yea I noticed that afterward, I got the proper validation errors on the field when trying to replicate.

**Comment by giovanniorigins** [comment]
![image](https://cloud.githubusercontent.com/assets/1894949/25671734/0a5cff5e-2fff-11e7-89ec-0e16db4bc81d.png)

**Comment by nkeena** [comment]
Strange. I'm not getting those error messages. Also, one of our test users said the airline list didn't populate for them. I tested myself and it does populate. Any thoughts @giovanniorigins ?

**Comment by giovanniorigins** [comment]
Lets try auto-populating and see if they still have that issue. can they check if there are any errors in their console log?

**Comment by nkeena** [comment]
Yes, I'll have them check.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/03/17 - 05/03/17
Work session total: 0:36:26
Grand total: 0:36:26
