### ISSUE TITLE
User provided explanation of why international travel isn't needed

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#519]
It's come to my attention that when a user indicates they don't need an international flight to the destination country, staff will need an explanation from the user as to why.

Also, if the user indicates they don't need arrangements for their return home, staff really needs to know why.

One solution could be to use an `activity`'s `description` property. When a user selects the option to arrange their own transportation to the destination country, an "Please Explain why:" text area could appear. This would be tied to the `activity`'s `description` property.

<img width="546" alt="screen shot 2017-05-03 at 12 40 55 pm" src="https://cloud.githubusercontent.com/assets/4267904/25671388/d35b1870-2ffd-11e7-86b8-9dae719e8845.png">

If a user checks the I don't need a return international flight, then the return home activity item should only require a "Please explain why" text area. This would be tied to the the `activity`'s `description` property. A transport and hub should not be sent with that activity in this case.

So the request could look something like:

```
{
    "items": [
        {
            "activity": {...},
            "transport": {...},
            "hub": {...}
        },
        {
            "activity": { "description": ....}
        }
    ]
}
```

<img width="577" alt="screen shot 2017-05-03 at 12 41 11 pm" src="https://cloud.githubusercontent.com/assets/4267904/25671392/d787300a-2ffd-11e7-84f6-a86b8c09ebc8.png">

**Comment by nkeena** [comment]
Let's move this into the "Return Home" item, and instead of removing the item, we show only a "Please Explain why" text area.

![](https://cloud.githubusercontent.com/assets/4267904/25671392/d787300a-2ffd-11e7-84f6-a86b8c09ebc8.png)

**Comment by giovanniorigins** [comment]
okay, working on this now

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/03/17 - 05/03/17
Work session total: 1:42:56
Grand total: 1:42:56
