### ISSUE TITLE
Team Manager Bugs & Improvements

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#522]
- [x] Members in "team leader" group don't show companion notification

- [x] Remove gender restriction on team leader group

- [x] Members column filter button doesn't open filter's aside

- [x] Role filter not working for reservations

- [x] Team types with a max of 1 squad when creating a new team throw an error saying the maximum number of groups have been reach. No groups are created and the team type rules are not displayed in the details. This seems to work after manually adding a group.

<img width="680" alt="screen shot 2017-05-03 at 4 47 27 pm" src="https://cloud.githubusercontent.com/assets/4267904/25680895/5c6829ec-3020-11e7-80f8-fc3b356b7924.png">

- [x] Add team type label next to team name in teams list

- [x] Member count and team count in tabs are not updating dynamically. Won't update until page is refreshed.

- [x] Campaign selector at top does not populate with campaign names on search.

**Comment by giovanniorigins** [comment]
Members column filter button doesn't open filter's aside: 
What filters do we want for members?

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/04/17 - 05/04/17
Work session total: 2:51:17
Grand total: 2:51:17

**Comment by nkeena** [comment]
<img width="685" alt="screen shot 2017-05-09 at 4 57 42 pm" src="https://cloud.githubusercontent.com/assets/4267904/25872701/b20cbe72-34d9-11e7-8824-49a3faba2b3b.png">

Displaying this message even though the team's rules say they must have a minimum of 2 team leaders.

<img width="707" alt="screen shot 2017-05-09 at 4 57 18 pm" src="https://cloud.githubusercontent.com/assets/4267904/25872751/dc3eee4a-34d9-11e7-90d7-849039dfde5a.png">

Groups are not in order.

<img width="651" alt="screen shot 2017-05-09 at 4 59 27 pm" src="https://cloud.githubusercontent.com/assets/4267904/25872761/e631a24e-34d9-11e7-83ad-f0b757448471.png">

Don't see the option to move a member to another group only as that group's leader?

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/09/17 - 05/09/17
Work session total: 1:02:28
Grand total: 3:53:45

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/10/17 - 05/10/17
Work session total: 3:22:15
Grand total: 7:16:00

**Comment by nkeena** [comment]
Members already assigned to a group get added as duplicates when the add companion button is used.

<img width="695" alt="screen shot 2017-05-11 at 3 11 50 pm" src="https://cloud.githubusercontent.com/assets/4267904/25967786/3fa66844-365d-11e7-8232-cf4fc0ec4316.png">

<img width="679" alt="screen shot 2017-05-11 at 3 12 00 pm" src="https://cloud.githubusercontent.com/assets/4267904/25967787/41bd0cb4-365d-11e7-902a-9935f7d09bb2.png">

**Comment by nkeena** [comment]
When searching for a role, it seems to be pulling for existing roles on the reservations instead of all available roles which produces duplicates...

<img width="373" alt="screen shot 2017-05-11 at 9 43 25 am" src="https://cloud.githubusercontent.com/assets/4267904/25967822/5a575ea0-365d-11e7-9f22-57dabcd74830.png">

**Comment by giovanniorigins** [comment]
that is strange, it is supposed to be listing roles from the API

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/11/17 - 05/11/17
Work session total: 1:28:27
Grand total: 8:44:27

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/18/17 - 05/18/17
Work session total: 0:00:01
Grand total: 8:44:28
