### ISSUE TITLE
Travel Itinerary Error

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#528]
Need hotfix asap.

![screen shot 2017-05-09 at 5 29 19 pm](https://cloud.githubusercontent.com/assets/4267904/25873612/2fc09d54-34dd-11e7-8eb1-cb1cfbd9ec7f.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/09/17 - 05/09/17
Work session total: 0:11:52
Grand total: 0:11:52
