### ISSUE TITLE
Admin Team Type Mangagement

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#542]
As an admin, I would like to have access to a list of all team types, edit those types, add new types, and delete types so that Team Facilitators have new or updated choices to choose from.

**Comment by nkeena** [comment]
@giovanniorigins, in the admin, let's add a tab under the campaign details called "Teams". We could maybe have some kind of sub-navigation to see a list of team types and actual teams.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/16/17 - 05/17/17
Work session total: 3:39:51
Grand total: 3:39:51

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/17/17 - 05/17/17
Work session total: 4:41:49
Grand total: 8:21:40

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/18/17 - 05/18/17
Work session total: 0:00:23
Grand total: 8:22:03
