### ISSUE TITLE
Travel Requirements not showing because of missing $root user

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#545]
Travel requirements are loading sometimes. The possible reason is it appears that the `$root.user` object is being cleared or not repopulated. Cause is unknown. Maybe an expired cookie? Session expiration and `$root.user` storage don't seem to be in sync sometimes.

**Comment by giovanniorigins** [comment]
I've experimented with session timeouts etc and i can confirm that it happens specifically  when the user data is removed from `localStorage`. However the user data is only supposed to be deleted when the `api_token` cookie is no longer present.
```javascript
// if api_token cookie doesn't exist user data will be cleared if they do exist
        if (this.$cookie.get('api_token') === null) {
            if (localStorage.hasOwnProperty('user'))
                localStorage.removeItem('user');
            if (localStorage.hasOwnProperty('impersonatedUser'))
                localStorage.removeItem('impersonatedUser');
        } else {
            // because user is computed, this must be called to initiate impersonation or normal user before anything else
            this.user;
        }
```
This may mean that the `api_token` cookie is expiring at some point. I had not added logic to react to this case so in my PR i will add logic that will logout the user if the `api_token` cookie is missing and they are present in the dashboard or admin. 

This doesn't really solve the cookie expiration issue that i believe may be the cause, but at least it will prevent the user from being confused as to what is happening - prompting them to log in again.

**Comment by giovanniorigins** [comment]
Improving on this solution, we now attempt to retrieve the user data from the API `users/me` if this fails we know for certain that the `api_token` has either been invalidated, removed, or expired, so the user is finally logged out.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/18/17 - 05/18/17
Work session total: 3:14:15
Grand total: 3:14:15

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/19/17 - 05/19/17
Work session total: 2:10:40
Grand total: 5:24:55
