### ISSUE TITLE
As an admin, I want to search squads by name and filter them by a group so I can find the squad(s) I'm looking for

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#557]
**User Story**
As an admin, I want to search squads by name and filter them by a group so I can find the squad(s) I'm looking for.

**Acceptance Criteria**
- See search input over squads list for admins only
- Can search a squad by name
- See filter button over squads list for admins only
- Can filter squads by a group

**Comment by nkeena** [comment]
@giovanniorigins,
New group filter has been added. Check the wiki for updated docs on teams endpoint. You can already search by `callsign`. That should be all you need from me to complete this issue.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/23/17 - 05/23/17
Work session total: 1:45:57
Grand total: 1:45:57

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/24/17 - 05/24/17
Work session total: 0:35:14
Grand total: 2:21:11
