### ISSUE TITLE
As an admin, I want to assign a squad to a group when I create it so that it belongs to a group

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#558]
**User Story**
As an admin, I want to assign a squad to a group when I create it so that it belongs to a group.

**Acceptance Criteria**
- Only admins see a searchable dropdown of groups in the create squad modal
- Can select a group from the dropdown
- Associates the squad to the group
- Only admins see the squad's travel group name under the squad name in the squads' list

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/23/17 - 05/23/17
Work session total: 0:33:59
Grand total: 0:33:59
