### ISSUE TITLE
Team is not being associated with it's travel group when created

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#560]
When creating a team for a group in the dashboard, the group isn't being associated with the group.

See: https://github.com/missions-me/missions/wiki/Teams#team-associations

This issue also revealed that teams are not being scoped to their parent groups. After testing this, it seems that every group has access to all teams created.

**Comment by giovanniorigins** [comment]
I just created a team, this is what was sent in the payload:
![image](https://cloud.githubusercontent.com/assets/1894949/26372540/5021987e-3fcc-11e7-8ca6-31353c5d67c3.png)
does your look similar when creating one?

**Comment by nkeena** [comment]
Yep, I'm getting the same thing. So the correct payload is being sent but it's not saving the groups in the database. Looks like an API issue
