### ISSUE TITLE
As a user, I want to filter the squad' list in rooming by arrival designation so I can assign them to rooms

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#562]
**User Story**
As a user, I want to filter the squads' list in room by arrival designation so I can assign them to rooms

**Acceptance Criteria**
- [x] See filter by Arrival Designation
- [x] See arrival designation under the team member's details
- [x] Can filter by Arrival Designation
- [x] See arrival designation under the occupant's details

**Definition of Done**
- passes all tests
- meets acceptance criteria
- passes review and QA cycle

**Comment by giovanniorigins** [comment]
@nkeena I can't find the filter for these, has it been added yet?

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/27/17 - 05/27/17
Work session total: 1:03:55
Grand total: 1:03:55

**Comment by nkeena** [comment]
@giovanniorigins this filter is found in the `ReservationFilter` class.

```php
/**
     * By arrival designation type
     * 
     * @param  String $type
     * @return Builder
     */
    public function designation($type)
    {   
        if ($type === 'none') {
            return $this->has('designation', '<', 1);
        }

        return $this->wherehas('designation', function ($designation) use ($type) {
            return $designation->where('content', 'LIKE', "%$type%");
        });
    }
```

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/31/17 - 05/31/17
Work session total: 1:42:45
Grand total: 2:46:40
