### ISSUE TITLE
As an admin, I want to manage regions for a campaign

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#565]
**User Story**
As an admin, I want to manage regions for a campaign.

**Comment by nkeena** [comment]
Documentation:
https://github.com/missions-me/missions/wiki/Regions

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/25/17 - 05/25/17
Work session total: 1:10:28
Grand total: 1:10:28
