### ISSUE TITLE
As an admin, I want to see a list of regions I can search and filter so that I can find the regions I want

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#566]
**User Story**
As an admin, I want to see a list of regions I can search and filter so that I can find the regions I want.

**Acceptance Criteria**

- [x] See list of regions in admin under the scope of a campaign (tab: Regions)
- [x] Can search regions by name and callsign
- [x] Can filter regions by country code
- [x] Can see teams count for each region
- [x] Can see which travel groups (from teams) are in each region

**Definition of Done**

- Meets acceptance criteria
- Passes all tests
- Passes review and QA cycle

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/24/17 - 05/24/17
Work session total: 4:21:11
Grand total: 4:21:11
