### ISSUE TITLE
As an admin, I want to delete a region so that it is removed from the list

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#569]
**User Story**
As an admin, I want to delete a region so that it is removed from the list.

**Acceptance Criteria**
- [x] Delete option with warning
- [x] Deleting a region automatically detaches all teams assigned to it (API)
- [x] See it removed from list immediately
- [x] See notification of successful deletion

**Definition of Done**
- Meets acceptance criteria
- Passes all tests
- Passes review and QA cycle

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/25/17 - 05/25/17
Work session total: 0:12:33
Grand total: 0:12:33
