### ISSUE TITLE
As an admin, I want to see a list of teams (squads) to search and filter so that I can assign them to a region

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#570]
**User Story**
As an admin, I want to see a list of teams (squads) to search and filter so that I can assign them to a region.

**Acceptance Criteria**
- [x] See list of teams for the given campaign that are not in the selected region
- [x] See team's name, callsign, type, and number of members for each team in list
- [x] Can search by team's callsign
- [x] Can filter by team's travel group
- [x] Can filter by team type
- [x] Can filter teams assigned to no regions
- [x] Can filter teams assigned to at least one region

**Definition of Done**
- Meets criteria
- Passes tests
- Passes review

**Comment by nkeena** [comment]
@giovanniorigins, I added the necessary filters to complete this issue. See updated docs: https://github.com/missions-me/missions/wiki/Teams#filter-teams

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/25/17 - 05/25/17
Work session total: 4:36:30
Grand total: 4:36:30
