### ISSUE TITLE
As an admin, I want to add squads to a region and see those squads in the region so that I can assign squads to regions

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#571]
**User Story**
As an admin, I want to add squads to a region and see those squads in the region so that I can assign squads to regions.

**Acceptance Criteria**
- [x] See button for adding squad to the selected region
- [x] See the squad listed under the region selected after adding it
- [x] Do not see the squad in squads list while region is selected
- [x] See button to remove the squad from the region
- [x] Squad disappears from region and re-appears in quads list
- [x] Squads count increases or decreases in the regions list as squads are added or removed

**Definition of Done**
- Meets criteria
- Passes tests
- Passes review

**Comment by nkeena** [comment]
@giovanniorigins, @zechnelson I imagine this could work almost identically to the way rooming does where we have a list of regions and area above that where a selected region would appear. As squads are added to the region, the region's squad count would increase or decrease in the list below, and the squads appear in the selected region above.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/24/17 - 05/24/17
Work session total: 0:17:18
Grand total: 0:17:18

**Comment by nkeena** [comment]
Fixes and improvements needed:

- [ ] Change squad list design
- [ ] Change selected region work area design
- [ ] Fix 405 error
- [ ] Show groups dynamically as squads are added
- [ ] Fix region edit for type
- [ ] Add "filter" label to filter buttons

![screen shot on jun 13th at 11-57 am](https://user-images.githubusercontent.com/4267904/27092598-e19958c6-5031-11e7-8a06-05ec80c5e3eb.png)

![screen shot on jun 13th at 11-58 am](https://user-images.githubusercontent.com/4267904/27092600-e389956a-5031-11e7-8369-a35479434ced.png)

**Comment by giovanniorigins** [comment]
@nkeena I don't get a 405 error on this, it creates successfully.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/13/17 - 06/13/17
Work session total: 0:54:52
Grand total: 1:12:10

**Comment by nkeena** [comment]
Let's implement the revised regions list design on this page...
![squad_assignments](https://user-images.githubusercontent.com/4267904/27197970-694c336c-51de-11e7-9866-5527533ed9cb.png)

The new design:
![regions_list](https://user-images.githubusercontent.com/4267904/27197977-6cca3840-51de-11e7-89c7-18ed7d538b50.png)

Squad types list should be dynamic and pull from the existing squad types available for the campaign:

<img width="431" alt="screen shot 2017-06-15 at 3 12 32 pm" src="https://user-images.githubusercontent.com/4267904/27198002-7ee33658-51de-11e7-8e9b-85b90a04b20f.png">

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/15/17 - 06/15/17
Work session total: 0:25:43
Grand total: 1:37:53
