### ISSUE TITLE
Default Rooming Plan Selection

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#576]
- [x] When a user creates a new rooming plan, that plan is selected by default.
- [x] The browser remembers and loads the most recent rooming plan used.
- [x] Hide room selection and squad selection until a plan is selected
- [x] Show text "Please select a rooming plan to get started" to the blank area under the tutorial when no plan is selected

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/27/17 - 05/27/17
Work session total: 0:21:54
Grand total: 0:21:54
