### ISSUE TITLE
As a user, I want to add squad members to rooms as occupants and see them in the room

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#577]
**User Story**
As a user, I want to add squad members to rooms as occupants and see them in the room.

**Acceptance Criteria**
- [x] Can add member to room as occupant
- [x] Member disappears from squad list and appears immediately in the room as an occupant.
- [x] Can remove members from a room
- [x] Member disappears from room and immediately appears back in the squads list
- [x] Squad list should only show members that do not have a room for the given rooming plan

**Definition of Done**
- Meets criteria
- Passes tests
- Passes review

**Comment by nkeena** [comment]
@zechnelson, @giovanniorigins,

Can we make this more natural sounding? I'm sure we can do it using conditonals

<img width="334" alt="screen shot 2017-05-24 at 3 28 02 pm" src="https://cloud.githubusercontent.com/assets/4267904/26421920/c56147c8-4095-11e7-905d-64adf62c2ecf.png">

Maybe something like:

- Total Occupants 1 of 4
- Must be same gender (only if true)
- Must be married (only if true)
- Room Leader (keep the same)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/27/17 - 05/27/17
Work session total: 1:16:42
Grand total: 1:16:42

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/28/17 - 05/28/17
Work session total: 0:05:13
Grand total: 1:21:55

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/30/17 - 05/30/17
Work session total: 0:27:53
Grand total: 1:49:48
