### ISSUE TITLE
As an admin, I want to manage accommodations for a region so I can provide an accommodation for rooms.

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#586]
**User Story**
As an admin, I want to create accommodations for a region so I can provide an accommodation for rooms.

**Acceptance Criteria**
- [x] See a list of accommodations in a selected region
- [x] See a form to create an accommodation with Name, Address, Description, Email, Phone, Fax, URL inputs
- [x] Create form validates input fields
- [x] Creates the accommodation for the region
- [x] Can edit the accommodation
- [x] Can delete the accommodation

** Definition of Done**
- [ ] Meets criteria
- [ ] Passes tests
- [ ] Passes review

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 05/31/17 - 05/31/17
Work session total: 2:34:50
Grand total: 2:34:50

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/01/17 - 06/01/17
Work session total: 6:19:22
Grand total: 8:54:12

**Comment by giovanniorigins** [comment]
@nkeena, got this error when trying to associate a plan to an accommodation:
`message:"That type of room cannot be added."`

```javascript
class:"Exception"
file:"/Users/jerezb/Sites/missions/app/Services/Rooming/ValidatesRooms.php"
line:35
```
last 5 trails in the trace:
```javascript
0:"#0 /Users/jerezb/Sites/missions/app/Services/Rooming/ValidatesRooms.php(27): App\Services\Rooming\ValidatesRooms->assertAllowsRoomType(NULL)"
1:"#1 /Users/jerezb/Sites/missions/vendor/laravel/framework/src/Illuminate/Support/Collection.php(206): App\Services\Rooming\ValidatesRooms->App\Services\Rooming\{closure}(Object(App\Models\v1\Room), 0)"
2:"#2 /Users/jerezb/Sites/missions/app/Services/Rooming/ValidatesRooms.php(29): Illuminate\Support\Collection->each(Object(Closure))"
3:"#3 /Users/jerezb/Sites/missions/app/Traits/Roomable.php(11): App\Services\Rooming\ValidatesRooms->validate()"
4:"#4 /Users/jerezb/Sites/missions/app/Services/Rooming/ManageRooms.php(27): App\Repositories\Rooming\EloquentAccommodation->addRooms(Array, 'eec0758a-8479-4...')"
```

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/06/17 - 06/06/17
Work session total: 4:13:55
Grand total: 13:08:07

**Comment by nkeena** [comment]
@giovanniorigins , it looks like the reason you got the error is because a room type in the plan is not allowed in the accommodation. They will need to match. In my opinion, it's working like it should. 

Do you think it will be confusing for the admin?

**Comment by giovanniorigins** [comment]
@nkeena Ohh, i see that the room type didn't match any of the types i had in my DB, yea it seems to be working fine. You mean the error or the component?

**Comment by nkeena** [comment]
I mean the error. I just want it to be obvious that only certain room types are allowed. We do list the room types under the accommodation like we do the rooming plan, correct?

**Comment by giovanniorigins** [comment]
The error was fine I believe, it was just that it was unexpected for me.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/07/17 - 06/07/17
Work session total: 0:01:08
Grand total: 13:09:15

**Comment by nkeena** [comment]
Changes/Improvements:

- [ ] Add titles
- [ ] Fix state and zip not saving issue
- [ ] Add available room types inputs to create/edit
- [ ] Alternate solution to modal or maybe two column modal approach?
- [ ] Add "fitler" labels to filter buttons
- [ ] Changes to regions list
- [ ] Can dynamically change a label's color by using the region's callsign as an HTML color name

https://en.wikipedia.org/wiki/Web_colors

![screen shot on jun 13th at 12-27 pm](https://user-images.githubusercontent.com/4267904/27093201-d1e87248-5033-11e7-8a12-78df13d7b24b.png)

**Comment by nkeena** [comment]
Changes/Improvements:

- [ ] Add titles
- [ ] Fix state and zip not saving issue
- [ ] Add available room types inputs to create/edit
- [ ] Alternate solution to modal or maybe two column modal approach?
- [ ] Add "fitler" labels to filter buttons
- [ ] Changes to regions list
- [ ] Can dynamically change a label's color by using the region's callsign as an HTML color name

https://en.wikipedia.org/wiki/Web_colors

![screen shot on jun 13th at 12-27 pm](https://user-images.githubusercontent.com/4267904/27093201-d1e87248-5033-11e7-8a12-78df13d7b24b.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/13/17 - 06/13/17
Work session total: 2:18:14
Grand total: 15:27:29

**Comment by nkeena** [comment]
@giovanniorigins, clicking "Create an accommodation" doesn't seem to be working for me.

**Comment by nkeena** [comment]
These need to be dynamic:

![room_types](https://user-images.githubusercontent.com/4267904/27198092-cf036734-51de-11e7-9c37-9d3aae1fac85.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/15/17 - 06/15/17
Work session total: 0:19:51
Grand total: 23:49:19
