### ISSUE TITLE
As an admin, I want to use a rooming plan with an accommodation to quickly add rooms

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#587]
**User Story**
As an admin, I want to use a rooming plan for an accommodation in order to quickly add rooms.

**Acceptance Criteria**
- [x] See list of rooms in an accommodation
- [x] Filter that list by rooming plan or room types
- [x] See a list of rooming plans scoped to campaign
- [x] Filter list of rooming plans by group

**Definition of Done**
- Meets Criteria
- Passes Tests
- Passes Review

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/01/17 - 06/01/17
Work session total: 0:31:23
Grand total: 0:31:23

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/02/17 - 06/02/17
Work session total: 5:48:48
Grand total: 6:20:11

**Comment by nkeena** [comment]
![rooming_accommodations_1](https://user-images.githubusercontent.com/4267904/27198609-e492a25c-51e0-11e7-9358-5107b62d87e0.png)

![rooming_accommodations_2](https://user-images.githubusercontent.com/4267904/27198611-e6a0a18e-51e0-11e7-833c-8a5807d07cdf.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/15/17 - 06/15/17
Work session total: 0:23:37
Grand total: 6:43:48

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/16/17 - 06/16/17
Work session total: 1:26:04
Grand total: 8:09:52
