### ISSUE TITLE
As an admin, I want to add reservations as passengers to transports 

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#593]
- [x] Can add or remove reservations to transport as passengers
- [x] Can search and filter reservations list
- [x] Can search passengers list
- [x] Can filter passengers by groups, role, age, gender, hasCompanions, designation
- [x] See warning notification that passenger's companions are not with them
- [x] Button to add a passenger's companions to the transport

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/12/17 - 06/12/17
Work session total: 0:00:16
Grand total: 0:00:16

**Comment by nkeena** [comment]
https://realtimeboard.com/app/board/o9J_k0BIuLc=/

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/19/17 - 06/19/17
Work session total: 0:01:14
Grand total: 0:01:30

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/20/17 - 06/20/17
Work session total: 2:22:19
Grand total: 2:23:49

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/21/17 - 06/21/17
Work session total: 2:22:39
Grand total: 4:46:28

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/06/17 - 07/06/17
Work session total: 0:00:09
Grand total: 6:15:42
