### ISSUE TITLE
As an admin, I want to create and edit travel itineraries for transports

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#594]
- [x] See list of activities scoped to the transport
- [x] Search activities by name/description
- [x] Filter by activity type
- [x] Filter by date range
- [x] Expand an activity to see connected "hub" details
- [x] See button to add new activities
- [x] Can add a new activity
- [x] Can edit an activity
- [x] Can delete an activity
- [x] Can add/edit/remove hubs connected to activities

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/12/17 - 06/12/17
Work session total: 0:24:25
Grand total: 0:24:25

**Comment by nkeena** [comment]
https://realtimeboard.com/app/board/o9J_k0BIuLc=/

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/19/17 - 06/20/17
Work session total: 5:58:02
Grand total: 6:22:27

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/20/17 - 06/20/17
Work session total: 2:25:29
Grand total: 8:47:56

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/21/17 - 06/21/17
Work session total: 3:47:58
Grand total: 12:35:54

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/22/17 - 06/22/17
Work session total: 2:13:19
Grand total: 14:49:13

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/11/17 - 07/11/17
Work session total: 0:55:00
Grand total: 15:44:13

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/12/17 - 07/12/17
Work session total: 1:32:31
Grand total: 17:16:44
