### ISSUE TITLE
As an Admin, I want to define the type of rooms that can be added to rooming plan so that not any type of room can be added

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#617]
**User Story**
As an Admin, I want to define the type of rooms that can be added to rooming plan so that not any type of room can be added.

**Acceptance Criteria**
- [x] See "settings" button to access rooming plan settings
- [x] Add or remove room types with number of available rooms to the plan
(Rooms being created will get validate by the API based on what room types are assigned here and how many rooms of that type are allowed)

**Definition of Done**
- [ ] Meets criteria
- [ ] Passes tests
- [ ] Passes review

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/05/17 - 06/05/17
Work session total: 3:25:08
Grand total: 3:25:08

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/06/17 - 06/06/17
Work session total: 0:02:06
Grand total: 3:27:14
