### ISSUE TITLE
As an admin, I want to add or remove groups that are associated with a team (squad)

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#627]
**User Story**
As an admin, I want to add or remove groups that are associated with a team (squad).

**Acceptance Criteria**
- [x] See list of groups associated with the squad under squad details
- [x] Add groups to the squad
- [x] Remove groups from the squad

**Definition of Done**
- Meets criteria
- Passes review

**Comment by nkeena** [comment]
<img width="682" alt="screen shot 2017-06-02 at 4 59 41 pm" src="https://cloud.githubusercontent.com/assets/4267904/26744741/415239b6-47b5-11e7-87f9-3af5f7568c7e.png">

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/03/17 - 06/04/17
Work session total: 2:43:20
Grand total: 2:43:20

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/04/17 - 06/04/17
Work session total: 1:24:48
Grand total: 4:08:08

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/05/17 - 06/05/17
Work session total: 4:35:53
Grand total: 8:44:01
