### ISSUE TITLE
Occupant is not set as room leader when added to room as leader

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#629]

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/03/17 - 06/03/17
Work session total: 0:36:48
Grand total: 0:36:48

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/16/17 - 06/16/17
Work session total: 2:06:41
Grand total: 2:43:29

**Comment by giovanniorigins** [comment]
is this still an issue?

**Comment by nkeena** [comment]
Yes, it seems to be. Last time I tested on Friday it was.

**Comment by giovanniorigins** [comment]
the info is being sent to the api correctly, but the return data, no leader was set. Even after demoting then adding as leader doesn't work

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/18/17 - 06/18/17
Work session total: 0:30:03
Grand total: 3:13:32

**Comment by giovanniorigins** [comment]
looking at the store controller, it looks that it is not using the room_leader property to assign the leader.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/18/17 - 06/19/17
Work session total: 0:58:34
Grand total: 4:12:06

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/20/17 - 06/20/17
Work session total: 0:00:05
Grand total: 4:12:11

**Comment by giovanniorigins** [comment]
this is fixed btw
