### ISSUE TITLE
As a user, I want to see a warning when an occupant's companions are not in the same room.

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#630]
**User Story**
As a user, I want to see a warning when an occupant's companions are not in the same room.

**Acceptance Criteria**
- [x] See companion warning on occupant card when added to a room

**Definition of Done**
- [ ] Meets criteria
- [ ] Passes review

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/03/17 - 06/03/17
Work session total: 1:04:48
Grand total: 1:04:48
