### ISSUE TITLE
Room Manager: See an occupant's companion names listed.

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#631]
**Acceptance Criteria**
- [x] See companion names in squad member card (like teams)
- [x] See companion names in occupant's card (like teams)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/02/17 - 06/03/17
Work session total: 0:24:57
Grand total: 0:24:57

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/03/17 - 06/03/17
Work session total: 0:11:12
Grand total: 0:36:09
