### ISSUE TITLE
As a user, I want to change a reservation's role in the reservation's list so that I can assign them to leadership positions on a squad

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#632]
**User Story**
As a user, I want to change a reservation's role in the reservation's list so that I can assign them to leadership positions on a squad.

**Acceptance Criteria**
- [x] See option to change reservation's role
- [x] Can only change role to two options (Squad Leader or Group Leader)
- [x] The `desired_role` on the reservation get's updated

**Definition of Done**
- [x] Meets criteria
- [x] Passes tests
- [ ] Passes review

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/02/17 - 06/02/17
Work session total: 1:01:16
Grand total: 1:01:16
