### ISSUE TITLE
Squads & Rooming Updates and Bug Fixes

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#644]
- [x] Add short description to create rooming plan modal (required field) @giovanniorigins 
- [x] Add short description to rooming plan settings modal (required field) @giovanniorigins 
- [x] Add name input to rooming plan settings modal (required field) @giovanniorigins 
- [x] Rooming plans filters not resetting @giovanniorigins 
- [x] Remove campaigns filter from rooming plans list @giovanniorigins 
- [x] Room leader should be at top of a room's occupant's list @giovanniorigins 
- [x] Show squad/group assignment(s) in reservation list drop-down @giovanniorigins 
- [x] Reservation list search not working on rooming @giovanniorigins 
- [x] Role and Travel Group filter not working for reservation list on rooming @giovanniorigins 
- [x] Squad Details - Group Leader is always at a count of 1 even when the squad is empty @giovanniorigins 
- [x] Squad not locking (missing in payload: `{"callsign":"Ministry 1"}`) @giovanniorigins 
- [x] Only squad name and locking should be editable not squad type @giovanniorigins 
- [x] Reservation list in rooming should be scoped to the selected rooming plan's group @giovanniorigins 
- [x] Rooming dashboard - use reservations list scoped to group and selected campaign instead of squad members list @giovanniorigins 
- [x] Add tab in admin under rooming for creating and managing room types @giovanniorigins 
- [x] See list of room types @giovanniorigins 
- [x] Add/Edit/Remove Room Types @giovanniorigins 

- [x] Change rooming plan list to data list instead of table @nkeena
- [x] Show short description in list @nkeena
- [x] Show room types allowed with counts in list @nkeena
- [x] Show travel group associated with rooming plan in list @nkeena
- [x] Show travel group associated with rooming plan in title @nkeena
- [x] Show rooming cost in occupant and reservation list drop-down @nkeena
- [x] Show designation on reservation list @nkeena
- [x] Show designation on squad member @nkeena
- [x] If occupant does not belong to a squad/group then indicate as "unassigned" @nkeena
- [x] Scope team types to campaign @nkeena
- [x] Scope room types to campaign @nkeena

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/09/17 - 06/10/17
Work session total: 5:39:54
Grand total: 5:39:54

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/10/17 - 06/10/17
Work session total: 0:40:30
Grand total: 6:20:24
