### ISSUE TITLE
Team & Room Manager Improvements/Bugfixes

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#649]
- [x] Can change a team member's role to squad leader or group leader just like in reservations list

| member list | reservation list |
| -------- | --------- |
| <img width="675" alt="screen shot 2017-06-12 at 9 36 11 pm" src="https://user-images.githubusercontent.com/4267904/27062213-837b8e0a-4fb7-11e7-83ee-048f892d5ede.png"> | <img width="490" alt="screen shot 2017-06-12 at 9 36 05 pm" src="https://user-images.githubusercontent.com/4267904/27062216-85b55156-4fb7-11e7-8622-5f231c44ad2c.png"> |

- [x] Show warning message that the team/group does not have a leader until one is assigned

<img width="563" alt="screen shot 2017-06-12 at 9 40 23 pm" src="https://user-images.githubusercontent.com/4267904/27062253-c391b726-4fb7-11e7-8283-dd536fca6261.png">
( maybe a red alert message like the green one that appears when a group/team is full? )

- [x] Rename all instances of Team to Squad in admin's campaign sub-nav 
- [x] Rename team rules labels
   -  Squad Type Settings:
    - Min Members -> Minimum Squad Members Required
    - Max Members -> Maximum Squad Members Allowed
    - Min Leaders -> Minimum Squad Leaders Required
    - Max Leaders -> Maximum Squad Leaders Allowed
    - Min Squads -> Minimum Groups Required
    - Max Squads -> Maximum Groups Allowed
    - Min Squad Members -> Minimum Members per Group
    - Max Squad Members -> Maximum Members per Group
    - Min Squad Leaders -> Minimum Leaders per Group
    - Max Squad Leaders -> Maximum Leaders per Group

- [x] Rename "Create Type" button to "Create Squad Type"

<img width="729" alt="screen shot 2017-06-12 at 1 54 58 pm" src="https://user-images.githubusercontent.com/4267904/27061759-7be820f2-4fb4-11e7-980a-9d8655d0f4e3.png">

- [x] Add group names separated by commas under the squad's name in the squad list.

<img width="1224" alt="screen shot 2017-06-12 at 1 56 49 pm" src="https://user-images.githubusercontent.com/4267904/27062019-309cabf2-4fb6-11e7-8da2-2936af7f61a3.png">

- [x] Same gender and married only input fields will not accept a value

<img width="1233" alt="screen shot 2017-06-12 at 2 02 54 pm" src="https://user-images.githubusercontent.com/4267904/27062319-3febd86a-4fb8-11e7-8223-3abb147cdf72.png">

**Comment by nkeena** [comment]
![Screen Shot 2017-06-13 at 3:10 PM](http://marker.screenshots.prod.s3.amazonaws.com/9e31c2a5aeea48218a09e9c317f6defc-1497366615550.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/13/17 - 06/13/17
Work session total: 2:32:26
Grand total: 2:32:26
