### ISSUE TITLE
Reservations Filter Component

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#658]
Create a reusable and customizable component for filter reservation lists.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/16/17 - 06/16/17
Work session total: 2:34:03
Grand total: 2:34:03

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/17/17 - 06/17/17
Work session total: 6:52:50
Grand total: 9:26:53

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/26/17 - 06/26/17
Work session total: 2:50:01
Grand total: 12:16:54

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/27/17 - 06/27/17
Work session total: 2:57:30
Grand total: 15:14:24

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/29/17 - 06/30/17
Work session total: 4:37:27
Grand total: 19:51:51

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 06/30/17 - 06/30/17
Work session total: 7:52:29
Grand total: 27:44:20

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/01/17 - 07/01/17
Work session total: 0:00:23
Grand total: 27:44:43
