### ISSUE TITLE
As an Admin, I want to associate multiple groups with a rooming plan so I can add reservations from multiple groups to the plan.

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#685]
**User Story**
As an Admin, I want to associate multiple groups with a rooming plan so I can add reservations from multiple groups to the plan.

**Acceptance Criteria**
- [x] Add groups to plan
- [x] Remove groups from plan
- [x] Multi-select group dropdown
- [x] Reservation list refreshes on group changes
- [x] Reservation list is scoped to selected groups

**Definition of Done**
- [x] Meets criteria
- [x] Passes tests
- [x] Passes review

**Comment by giovanniorigins** [comment]
tested and pushed the changes. However the last two, `Reservation list refreshes on group changes` and `Reservation list is scoped to selected groups` are these for rooming?

**Comment by nkeena** [comment]
Yes for rooming

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/03/17 - 07/03/17
Work session total: 1:03:04
Grand total: 1:03:04

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/04/17 - 07/04/17
Work session total: 0:42:22
Grand total: 1:45:26
