### ISSUE TITLE
Refactoring: Seperate reservations list and filters to own component

### ISSUE THREAD

**Issue by jgiovanni** [missions-me/missions#723]
- [x] Using Vue2
- [x] List items display data conditionally by purpose (squads, rooms, transports, etc.)
- [x] Uses events to communicate with other components
- [ ] Unit Tests

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/22/17 - 07/22/17
Work session total: 0:25:31
Grand total: 0:25:31

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 07/23/17 - 07/23/17
Work session total: 1:31:34
Grand total: 1:57:05

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/02/17 - 09/02/17
Work session total: 1:17:36

Grand total: 3:14:41

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/04/17 - 09/04/17
Work session total: 0:16:08

Grand total: 3:30:49

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/05/17 - 09/05/17
Work session total: 7:10:25

Grand total: 10:41:14

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/06/17 - 09/06/17
Work session total: 1:22:37

Grand total: 12:03:51

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/09/17 - 09/09/17
Work session total: 0:47:56

Grand total: 12:51:47

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/11/17 - 09/11/17
Work session total: 1:12:47

Grand total: 14:04:34

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/14/17 - 09/14/17
Work session total: 1:38:36

Grand total: 15:43:10

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/15/17 - 09/15/17
Work session total: 0:15:10

Grand total: 15:58:20

**Comment by jgiovanni** [comment]
Sooo, I'd like to complete these unit tests, but Vue-Strap is causing issues when running tests. trying to work around it still...

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/17/17 - 09/17/17
Work session total: 0:40:31

Grand total: 16:38:51

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/18/17 - 09/18/17
Work session total: 0:00:06

Grand total: 16:38:57
