### ISSUE TITLE
Upgrade to Vue 2

### ISSUE THREAD

**Issue by jgiovanni** [missions-me/missions#725]
- [x] Upgrade all components
- [x] Switch to Webpack
- [x] Update plugins
- [x] Test Components: Wizards and Events

### Breaking Changes:
- Some `Vue-Strap` components will need to be duplicated and edited for our needs because they are not fully compatible with the latest version of vue 2 (as of the comment - 2.4.2)
- Filters used on `v-model` will need to be converted to custom components i.e. `phone-input` or `date-input`
- custom validators are unnecessary
- some computed properties will need manual getter and setter functions, i.e `user` in `main.js`
- `$broadcast` and `$dispatch` have been eliminated. To reach the parent element `@event-name` needs to be added to child component in parent component for the event to register. $emit fired down scope work as normal.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/07/17 - 08/07/17
Work session total: 5:59:56
Grand total: 5:59:56

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/08/17 - 08/09/17
Work session total: 7:56:16
Grand total: 13:56:12

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/09/17 - 08/09/17
Work session total: 9:37:03
Grand total: 23:33:15

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/10/17 - 08/10/17
Work session total: 5:47:12
Grand total: 29:20:27

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/11/17 - 08/11/17
Work session total: 7:16:42
Grand total: 36:37:09

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/12/17 - 08/12/17
Work session total: 3:30:56
Grand total: 40:08:05

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/13/17 - 08/13/17
Work session total: 2:44:55
Grand total: 42:53:00

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/14/17 - 08/14/17
Work session total: 6:37:17
Grand total: 49:30:17

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/15/17 - 08/15/17
Work session total: 2:58:11
Grand total: 52:28:28

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/16/17 - 08/16/17
Work session total: 10:02:38
Grand total: 62:31:06

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/17/17 - 08/17/17
Work session total: 9:40:28
Grand total: 72:11:34

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/18/17 - 08/18/17
Work session total: 5:18:57

Grand total: 77:30:31

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/19/17 - 08/19/17
Work session total: 9:43:12

Grand total: 87:13:43

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/20/17 - 08/20/17
Work session total: 0:29:17

Grand total: 87:43:00

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/29/17 - 08/30/17
Work session total: 4:35:32

Grand total: 92:18:32

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/30/17 - 08/30/17
Work session total: 5:06:12

Grand total: 97:24:44

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/31/17 - 08/31/17
Work session total: 9:33:11

Grand total: 106:57:55

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/01/17 - 09/01/17
Work session total: 2:41:20

Grand total: 109:39:15

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/11/17 - 09/11/17
Work session total: 0:55:19

Grand total: 110:34:34

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/12/17 - 09/12/17
Work session total: 1:41:07

Grand total: 112:15:41

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/13/17 - 09/13/17
Work session total: 1:09:45

Grand total: 113:25:26

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/14/17 - 09/14/17
Work session total: 0:04:37

Grand total: 113:30:03

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/18/17 - 09/18/17
Work session total: 2:41:54

Grand total: 116:11:57

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/19/17 - 09/20/17
Work session total: 2:14:43

Grand total: 118:26:40

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/20/17 - 09/20/17
Work session total: 0:41:39

Grand total: 119:08:19

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/27/17 - 09/27/17
Work session total: 4:33:29

Grand total: 123:41:48

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/28/17 - 09/28/17
Work session total: 1:33:53

Grand total: 125:15:41

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/29/17 - 09/29/17
Work session total: 4:16:49

Grand total: 129:32:30
