### ISSUE TITLE
Upgrade vue-validator plugin

### ISSUE THREAD

**Issue by jgiovanni** [missions-me/missions#726]
Current Validator is unsupported by vue2 we need to switch to another.
Recommended: https://github.com/baianat/vee-validate

**Comment by nkeena** [comment]
@giovanniorigins, which validator plugin to you have in mind? A plugin that supports the following would be ideal:

- Can validate dynamic inputs
- Responds to server-side validation

**Comment by giovanniorigins** [comment]
Yea, i recommend this: https://github.com/baianat/vee-validate 
it is quite robust and 

- can handle server-side validation
- dynamic inputs
- inputs nested in other components like `vue-strap` components

**Comment by giovanniorigins** [comment]
A few notable breaking changes:
- `validator` component no longer used
- `v-validate` accepts only string
- all form validation will be redone

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/20/17 - 08/20/17
Work session total: 0:43:54

Grand total: 0:43:54

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/21/17 - 08/21/17
Work session total: 2:37:49

Grand total: 3:21:43

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/22/17 - 08/22/17
Work session total: 4:45:06

Grand total: 8:06:49

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/23/17 - 08/23/17
Work session total: 4:47:27

Grand total: 12:54:16

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/24/17 - 08/24/17
Work session total: 2:46:56

Grand total: 15:41:12

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/25/17 - 08/25/17
Work session total: 9:32:52

Grand total: 25:14:04

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/28/17 - 08/28/17
Work session total: 1:11:50

Grand total: 26:25:54

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/28/17 - 08/29/17
Work session total: 0:43:02

Grand total: 27:08:56
