### ISSUE TITLE
Refactor Donation Component

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#728]
In order to achieve PCI compliance, we must ensure user CC details never touch our server. This requires a refactor of the donation component(s).

It would be nice to use Stripe's Elements here:
https://stripe.com/docs/elements

Elements will generate a CC token and send that to the server.

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/06/17 - 09/06/17
Work session total: 1:59:39

Grand total: 1:59:39

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/07/17 - 09/07/17
Work session total: 1:22:16

Grand total: 3:21:55
