### ISSUE TITLE
Date Filters for Admin Transaction List are not working

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#735]
**URL**: https://missions.me/admin/transactions

**Description**
When selecting a date to filter by, no transaction details are displayed. Opening up the console and looking at the request, it appears that an `invalid date` is being passed to the filter parameters.

Here is the API request:
```
/api/transactions?include=donor%2Cfund&search=&per_page=10&page=1&sort=created_at%7Cdesc&fund=&donor=&minAmount=&maxAmount=&type=&maxDate=Invalid+date&minDate=Invalid+date&payment=
```

**Possibly bugged files**
- admin-transactions-list.vue
- date-picker.vue

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/14/17 - 08/14/17
Work session total: 0:34:52
Grand total: 0:34:52

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain
Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 08/15/17 - 08/15/17
Work session total: 2:59:48
Grand total: 3:34:40
