### ISSUE TITLE
As and admin I want to see a form to assign or remove roles from users

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#741]
**User Story**
As and admin I want to see a form to assign or remove roles from users

**Acceptance Criteria**
- [x] Can assign a role to a user
- [x] Can remove a role from a user
- [x] Can see which permissions a user has based on their role or roles

**Comment by nkeena** [comment]
@giovanniorigins, our current vue component for managing user roles and permissions will no longer work with the new updates to roles and permissions. I'd like you to spear head the development of a brand new component.

I think go with a simpler approach by only allow for the assignment of roles to the user rather than checking off individual permissions is a better route to take (at least for the first iteration).

Having to modify a specific user's permissions is rare and can easily be done manually in the database.

**Comment by nkeena** [comment]
@giovanniorigins, the big question is do we build in Vue1 or Vue2? If we can't get Vue2 successfully merged by September 11 then we'll need to go the vue1 route and then upgrade later.

**Comment by nkeena** [comment]
![screen shot 2017-09-01 at 12 12 08 pm](https://user-images.githubusercontent.com/4267904/29984329-d0925412-8f0e-11e7-88f7-e487cbcdc5da.png)

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/01/17 - 09/02/17
Work session total: 0:48:25

Grand total: 0:48:25

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/02/17 - 09/02/17
Work session total: 2:22:59

Grand total: 3:11:24
