### ISSUE TITLE
Laravel + Vue Upgrades Bug List

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#743]
This is an ongoing list of bugs introduced with the Laravel + Vue upgrade:

**Comment by nkeena** [comment]
## Stories are being rendered with HTML characters.

Example output:
```
<h1 id="story">Story</h1> <p>My cool story! <em>Hello world</em> More text...... <strong>hey</strong></p>
```
Instead of:
<h1 id="story">Story</h1> <p>My cool story! <em>Hello world</em> More text...... <strong>hey</strong></p> 

- [ ] RESOLVED

**Comment by giovanniorigins** [comment]
## Server-side Validation expecting validation for null properties
### Donation Requests
- `donor.company`
- `donor.phone`
- `comment`


## Example Error:
``` json
{
  {
    'comment' : ["The comment must be a string."],
    'donor.company' : ["The donor.company must be a string."],
    'donor.phone' : ["The donor.phone must be a string."],
  },
  message :"422 Unprocessable Entity"
}
```

**Comment by giovanniorigins** [comment]
## Policies Naming Issue
![image](https://user-images.githubusercontent.com/1894949/29982399-8e97f75e-8f1f-11e7-8e56-e511ce158dc6.png)

- [ ] RESOLVED

**Comment by nkeena** [comment]
## Trip Descriptions not rendering Markup

URL: /trips/{trip-id}

![screen shot 2017-09-01 at 9 40 08 am](https://user-images.githubusercontent.com/4267904/29982923-798590c2-8f08-11e7-842f-1de15a7e2c45.png)

- [ ] RESOLVED

**Comment by giovanniorigins** [comment]
## Campaign Transports page not loading

URL: `https://missions.dev/admin/campaigns/{campaign-id}/transports`
Page does not finish loading but outputs Error in console.
```
main.js?6e4b:599 Uncaught TypeError: Cannot read property 'content' of null
    at eval (eval at <anonymous> (main-1827a68f62.js:5372), <anonymous>:602:71)
    at Object.<anonymous> (main-1827a68f62.js:5372)
    at __webpack_require__ (main-1827a68f62.js:20)
    at main-1827a68f62.js:64
    at main-1827a68f62.js:67
```
After commenting out  `@inject('transport', 'App\CampaignTransport');` and `@can(...)...` code, the page loads fine.
- [ ] RESOLVED

**Comment by giovanniorigins** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/07/17 - 09/07/17
Work session total: 0:21:51

Grand total: 0:21:51

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/08/17 - 09/08/17
Work session total: 0:43:45

Grand total: 1:05:36
