### ISSUE TITLE
User Selection of Curated Fundraiser Images [5]

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#749]
### User Story

As a user, I want to select a featured image for my fundraising page from a curated collection provided by Missions.Me so that my fundraiser will look more professional.

### Acceptance Criteria

- [ ] User can preview a collection of available images
- [ ] User can select and apply the image of their choice
- [ ] User sees their selection updated on their fundraising page
- [ ] User can change this selection at any time
- [ ] Selected image appears as the thumbnail for a fundraiser card

**Comment by nkeena** [comment]
Yes, the banner selection image for user profiles. Maybe something similar.

@zechnelson what are your thoughts here? I know you mentioned about it not being a full-width banner...

**Comment by zechnelson** [comment]
Yea we have the functionality to upload images, however the problem we have is it's a little buggy at times so it's not super easy, and users aren't uploading their own content which leaves a fundraising page with no visual content. I think we should have 2-3 images that auto populate the slider, and then also allow users to pick from a list if they want to to change it. I just don't think they're spending the time to make their pages look good so we need to do it for them.

**Comment by nkeena** [comment]
Would we integrate that with the current "media manager" on the fundraising page? or are you suggesting that we scrap the upload tool?

**Comment by jgiovanni** [comment]
Is the featured image, the image that went behind the text 
```
Send {NAME} to {REGION}

Organized By {NAME}
```
?

**Comment by nkeena** [comment]
Canceling this feature in preference to the idea proposed in #767
