### ISSUE TITLE
Unique Page Titles [1]

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#750]
### User Story

As a user, I want to see unique page titles so that I better know which page I am and to provide a better link or page name when sharing on social medial.

### Acceptance Criteria

- [x] See a unique page title on every page
    - [x] Can add a custom title in each blade file
    - [x] Dynamic pages have dynamic page titles

**Comment by jgiovanni** [comment]
I would definitely recommend : [https://github.com/artesaos/seotools](url)

**Comment by nkeena** [comment]
OpenGraph Facebook best practices: https://developers.facebook.com/docs/sharing/best-practices#tags

Twitter Cards Markup reference: https://dev.twitter.com/cards/markup

**Comment by nkeena** [comment]
https://github.com/missions-me/missions/commit/d356bdd545772fe02c124a65895074654b5fcca5 closes this issue
