### ISSUE TITLE
Normalize User & Donor Names [8]

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#751]
### Enabler Story

Collect and store user and donor names in a normalized format of the first name and last name to increase data integrity and makes exporting to mailing lists and CRMs easier.

### Acceptance Criteria

- [x] Store names in two columns
    - [x] See user first_name and last_name
    - [x] See donor first_name and last_name
- [x] Collect names with two inputs
    - [x] User creation / edit forms 
    - [x] Donor creation / edit forms

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/12/17 - 09/12/17
Work session total: 0:00:04

Grand total: 0:00:04

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/13/17 - 09/13/17
Work session total: 3:00:06

Grand total: 3:00:10

**Comment by nkeena** [comment]
https://github.com/missions-me/missions/commit/db59c3b105f7ef30b09ee2d7671d64d104dc6927
