### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#760]
Invalid argument supplied error related to the `$essay->content` attribute. Only getting this error on influencer applications and not testimonies even though they are both `Essay` objects.

![screen shot 2017-09-21 at 11 48 02 am](https://user-images.githubusercontent.com/4267904/30719005-c24260e6-9ed6-11e7-91cb-217ad8c85e26.png)

- [x] RESOLVED

**Comment by nkeena** [comment]
Data not loading on influencer edit form
 
![screen shot 2017-09-21 at 11 48 36 am](https://user-images.githubusercontent.com/4267904/30719020-d3e58b02-9ed6-11e7-88c7-
2a5e2c45dd3f.png)

- [ ] RESOLVED

**Comment by nkeena** [comment]
Data not loading on media credentials edit form:

![screen shot 2017-09-21 at 11 26 52 am](https://user-images.githubusercontent.com/4267904/30719036-e52e7856-9ed6-11e7-9f24-8806eddd0b87.png)

- [ ] RESOLVED

**Comment by nkeena** [comment]
Data not loading on medical credentials edit form:

![screen shot 2017-09-21 at 11 27 26 am](https://user-images.githubusercontent.com/4267904/30719104-1db60da6-9ed7-11e7-9b88-77d22623a7ad.png)

- [ ] RESOLVED

**Comment by nkeena** [comment]
The file upload is showing required but it should not be.

![screen shot 2017-09-21 at 11 42 54 am](https://user-images.githubusercontent.com/4267904/30719161-44cb0446-9ed7-11e7-85de-43ab020f5b3c.png)

- [ ] RESOLVED

**Comment by nkeena** [comment]
Getting some display errors due to a missing ScrollMagic plugin:

![screen shot 2017-09-21 at 2 16 26 pm](https://user-images.githubusercontent.com/4267904/30719222-8161b7ce-9ed7-11e7-9fb2-6003981bf973.png)

- [ ] RESOLVED

**Comment by nkeena** [comment]
Admin table columns won't sort in the reverse direction. Getting this error:

```console
[Vue warn]: Error in render function: "TypeError: _.reverse is not a function"

found in

---> <AdminReservationsList> at /Users/neil/Sites/missions/resources/assets/js/components/reservations/admin-reservations-list.vue
       <Root>
```

- [ ] RESOLVED

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/21/17 - 09/22/17
Work session total: 2:01:30

Grand total: 2:01:30

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 09/22/17 - 09/22/17
Work session total: 0:21:45

Grand total: 2:23:15
