### ISSUE TITLE
Improve Fundraiser

### ISSUE THREAD

**Issue by jgiovanni** [missions-me/missions#767]
### User Story

As a fundraiser, I want to customize me page's feature image and description so that I can create a unique fundraiser page.

### Acceptance Criteria

- [x] Modular content creation (criteria)
    - [x] Header Module
    - [x] Image Module
    - [x] Text Module
    - [x] Video Module
- [x] Consider a content template that can be saved to the server efficiently
    - [x] Store order of content
    - [x] Store data
- [x] Use one API call to retrieve all content blocks and populate server-side or use Vue SSR
- [x] Content is reorder-able
- [x] Working mobile layout
- [x] Remind me modal to capture user email
- [x] Unique image names based on component instance.
    - Rename image file when replaced
    - Delete image file when component is removed
- [x] Custom Share buttons
- [x] Can Select or upload featured image.

**Comment by jgiovanni** [comment]
Images of content modules from wordpress. could be useful for ideas of future components. 
![image](https://user-images.githubusercontent.com/1894949/31149942-d28efe9a-a85f-11e7-8542-b4fce1a3defe.png)
![image](https://user-images.githubusercontent.com/1894949/31150022-1b35cade-a860-11e7-9156-e8ca951e9591.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/03/17 - 10/03/17
Work session total: 0:11:08

Grand total: 0:11:08

**Comment by jgiovanni** [comment]
Current progress:
![image](https://user-images.githubusercontent.com/1894949/31159145-f895a83e-a894-11e7-9994-fba1a6bc58cb.png)

Added Header widget
![image](https://user-images.githubusercontent.com/1894949/31159159-157fdc12-a895-11e7-8fd6-88a844fefe5c.png)

**Comment by jgiovanni** [comment]
![image](https://user-images.githubusercontent.com/1894949/31159173-2e338df8-a895-11e7-83f6-d9c49b1eba26.png)

**Comment by nkeena** [comment]
That's pretty cool.

I feel like one standard heading size is good enough for our purposes. Trying to minimize options so it doesn't overwhelm the user.

I like how Craft CMS lays out their content creation form....

![80554776-ba5a-e411-80dc-000d3a1003b1_2_full](https://user-images.githubusercontent.com/4267904/31187925-28d09420-a8e8-11e7-819e-67fce8e1668f.jpeg)

I'm thinking the "edit fundraiser" and "description" forms should be the same page. We could easily add static and required inputs at the top for "title", "short description" and "featured image".

![craft-dashboard](https://user-images.githubusercontent.com/4267904/31187963-52fe2816-a8e8-11e7-8635-952a61cdf7a4.png)

Adding helper text explaining the purpose of a field is important as well. I like how squarespace does it.

![code-injection](https://user-images.githubusercontent.com/4267904/31188052-98cfb526-a8e8-11e7-815d-2a9ed4c9f753.png)

Character counts could be helpful to users as well. Here's how contentful does it:

 
![contentful](https://user-images.githubusercontent.com/4267904/31188138-cbf890ee-a8e8-11e7-88a1-849145bfef3e.png)

**Comment by jgiovanni** [comment]
for the text block, do we want to use a text-editor or markdown?

**Comment by nkeena** [comment]
@zechnelson, I'm pulling you into this discussion so you're aware of what kind of content we're adding to fundraisers.

I really like how Kickstarter has the short one sentence description/tagline under the fundraiser's title at the top of the page. This could help solve the problem of communicating vision and intent of the fundraiser that a title just can't communicate alone.

We're planning to add a "short description" input to populate that space.

**Comment by nkeena** [comment]
I think we want to keep formatting options limited. I imagine a user does not need anything more than "bold" or "italic". 

The average user probably doesn't know or understand Markdown, so we shouldn't expect users to write in markdown unless we have a toolbar that inserts it for them.

Maybe we start with a simple textarea with no formatting options and then add those features in later?

**Comment by jgiovanni** [comment]
I've made some changes since last night, new images coming soon

**Comment by nkeena** [comment]
This is kinda cool how usabilityhub.com lets you re-order questions. This could work well here since we need exactly those three options.

<img width="585" alt="screen shot 2017-10-04 at 4 24 48 pm" src="https://user-images.githubusercontent.com/4267904/31204440-b2a05c8e-a920-11e7-9ad4-4192fb82b8b4.png">

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/04/17 - 10/04/17
Work session total: 6:09:40

Grand total: 6:20:48

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/05/17 - 10/05/17
Work session total: 5:09:33

Grand total: 11:30:21

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/06/17 - 10/06/17
Work session total: 3:21:15

Grand total: 14:51:36

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/09/17 - 10/09/17
Work session total: 4:13:05

Grand total: 19:04:41

**Comment by nkeena** [comment]
You've probably noticed that I've gone back and forth on the form design, lol. I think this is what we'll be sticking with. Helps to visually group what belongs to what.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/10/17 - 10/10/17
Work session total: 3:27:21

Grand total: 22:32:02

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/11/17 - 10/11/17
Work session total: 2:46:53

Grand total: 25:18:55

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/12/17 - 10/12/17
Work session total: 1:48:06

Grand total: 27:07:01

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/13/17 - 10/13/17
Work session total: 0:00:18

Grand total: 27:07:19

**Comment by nkeena** [comment]
@zechnelson here's the script tag you'll need for custom share buttons. Just replace the current one with this:

```
<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=58ba1e02535b950011d40583&product=custom-share-buttons"></script>
```

All you should need to add is a `data-network="facebook"` and a `data-network="twitter"` attribute to the buttons for them to work (according to the docs).

**Comment by nkeena** [comment]
@jgiovanni, here is an example of what we're looking for with the "remind me" modal:

<img width="464" alt="screen shot 2017-10-16 at 2 35 03 pm" src="https://user-images.githubusercontent.com/4267904/31636465-61eefed6-b27f-11e7-86b4-7d6de0fb1366.png">

Our copy: `Enter your email address and we'll remind you 48 hours before the deadline.`

**Comment by jgiovanni** [comment]
current route: `axios.post('utilities/reminder', { email: email})`

**Comment by nkeena** [comment]
@jgiovanni , don't forget we need to add an input to allow a user to select or upload a featured image for the fundraiser. That input should be located just under the title and short description on the "edit fundraiser" page.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/17/17 - 10/17/17
Work session total: 1:06:51

Grand total: 28:14:10

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/18/17 - 10/18/17
Work session total: 0:20:52

Grand total: 28:35:02

**Comment by nkeena** [comment]
Here’s a few things that need to happen when working with these images:
1) Image is uploaded on drop/input to `images/fundraiser_photos/{fundraiser_id}`
2) Image file name is `image_{unique_component_id}.{ext}`
3) When the image component is removed, the file should be deleted
4) The “Save Changes” button should be disabled while an image is uploading/processing to make sure a user doesn’t try to save changes with an incomplete upload

Here’s how I image the video component working:
1) When a user pastes a URL and clicks “attach” the input is replaced with the video player and the attached video.
2) User sees an option to “change video” that when clicked deletes the video upload object and shows the input again
3) If the video component is removed then the video upload object should also be deleted.
4) The “save changes” button should also be deleted while a video upload object is being created/deleted to make sure nothing gets lost if mid-transaction.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/26/17 - 10/27/17
Work session total: 3:18:28

Grand total: 31:53:30

**Comment by nkeena** [comment]
@jgiovanni, Are you encountering this issue?

When attaching a video or loading a fundraiser with a video in the edit form I see this error:

<img width="901" alt="screen shot 2017-10-27 at 9 40 07 am" src="https://user-images.githubusercontent.com/4267904/32115259-f4dc78c6-bafa-11e7-99ae-7691fca900cc.png">

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/27/17 - 10/27/17
Work session total: 2:00:29

Grand total: 33:53:59

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/30/17 - 10/30/17
Work session total: 1:49:59

Grand total: 35:43:58

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/31/17 - 10/31/17
Work session total: 2:55:04

Grand total: 38:39:02

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/01/17 - 11/01/17
Work session total: 3:57:27

Grand total: 42:36:29

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/02/17 - 11/02/17
Work session total: 0:45:06

Grand total: 43:21:35
