### ISSUE TITLE
Trip Reps

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#769]
### User Story

As an admin, I want to see a list of trip representatives so that I can create new ones, edit existing, or remove reps.

### Acceptance Criteria

- [x] Access a list of reps from `/admin/representatives`
- [x] See navigation link in toolbar
- [x] CRUD is authorized by user roles/permissions
- [x] See avatar, name, email, phone, and extention
- [x] Can add new rep
- [x] Can edit existing rep
- [x] Can delete rep
- [x] Forms validate
- [x] Can upload an avatar
- [x] Can see a preview of an avatar

**Comment by nkeena** [comment]
@jgiovanni can you help with the form validation and avatar upload?

**Comment by nkeena** [comment]
Getting this error from the `admin-trip-create-update` component:

```
Uncaught (in promise) TypeError: Cannot read property 'teamRolesList' of undefined
```

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/10/17 - 10/10/17
Work session total: 3:20:03

Grand total: 3:20:03

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/11/17 - 10/11/17
Work session total: 0:00:05

Grand total: 3:20:08
