### ISSUE TITLE
Avatar Upload Component

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#779]
Create an avatar specific component that provides a simple interface for uploading and previewing an avatar image.

- Avatars are always a 1:1 ratio and will normally be displayed as a square or circle (this can be handled with CSS).

- Avatars should be saved and uploaded in multiple formats optimized for screen sizes (i.e. mobile, retina, etc.) This can be accomplished server side using https://github.com/spatie/laravel-image-optimizer.

- Drag and drop as well as a button to browse should be incorporated into the design.

- Will need an easy way to add a preview image and set the url that will handle the upload. Using `props` could be a really nice way to do this. 
Concept: `:preview-image="pathToImage" :upload-url="pathToURL"`

<img width="292" alt="profilepicture02" src="https://user-images.githubusercontent.com/4267904/31456929-14f2203a-ae70-11e7-8377-69554c8b97f2.png">

![0a3889a2f0ec74365fbc1182863b1972--materialdesign-design-ui](https://user-images.githubusercontent.com/4267904/31456934-1746cbec-ae70-11e7-9f60-8d72b8f269d0.jpg)

### Why the Change?

The original idea for creating an uploads table and matching uploaded images to resources by idea was that it would evolve into a media manager. This idea doesn't seem to be that useful for our applications need and has added unnecessary complexity.

One of the problems with this approach is having to acquire an upload `id` whenever we want to add an image to something (i.e. user, group, campaign, etc.). This prevents us from easily assigning a new image by simply referencing a new path. Instead we have to upload a new image and create/update the the uploads table.

Another issue is the organization of images. With every upload being channeled through one endpoint, we have to depend on upload `types` and conditionals to determine or create image upload paths.

**Comment by jgiovanni** [comment]
what branch is this on?

**Comment by nkeena** [comment]
I'll create a new branch for it.

**Comment by nkeena** [comment]
We can use this branch: https://github.com/missions-me/missions/tree/feature-avatar-uploader

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/13/17 - 10/13/17
Work session total: 6:32:40

Grand total: 6:32:40
