### ISSUE TITLE
Fundraiser Donate Modal

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#783]
### User Story

As a user, I want to donate to the fundraiser I am viewing so that I can contribute to the project.

### Acceptance Criteria

- [x] Donation form opens in modal
    - Currently it slides open, unless the user scrolls down, the action could go unnoticed on smaller screens
    - New design does not accommodate this form of revealing the donation form
- [x] Success notification (Suggestion: Sweet alert is really good looking)
- [x] Reminder to share with sharing buttons after successful donation
- [x] Three Pre-defined amount options for the user to select ($10, $25, $50)
- [x] Improve overall design (see inspiration below)

![img1-2x](https://user-images.githubusercontent.com/4267904/31555610-8834b29c-aff6-11e7-82bd-b10be686810a.png)

**Comment by nkeena** [comment]
Let's also include a "other ways to give". We can display check donation information:

You can also donate by check. 
Please allow up to 14 business days for check donations to be processed.

Make checks payable to Missions.Me

Mail your check to:
145 S. Livernois Rd.
Suite 308
Rochester Hills, MI 48307

**Comment by nkeena** [comment]
I think the screenshot from donate.ly is a great example of a first step to the form. I also really like the non-obtrusive indicators at the bottom showing how many steps and which step you are on.

I think we can move all payment details to the second step.
Third step could be a review of the amount and last 4 of card with inputs for donor name (& company) along with a place for a comment.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/13/17 - 10/13/17
Work session total: 1:33:32

Grand total: 1:33:32

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/14/17 - 10/14/17
Work session total: 5:46:38

Grand total: 7:20:10

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/16/17 - 10/16/17
Work session total: 0:03:52

Grand total: 7:24:02

**Comment by nkeena** [comment]
Nice work @jgiovanni, works great!

@zechnelson I'm pulling you in to help with some UI changes

**Comment by nkeena** [comment]
<img width="360" alt="screen_shot_2017-10-16_at_2 25 25_pm_720" src="https://user-images.githubusercontent.com/4267904/31687080-1bf559f2-b33d-11e7-839d-cce1e26f7810.png">

<img width="322" alt="screen_shot_2017-10-16_at_2 25 42_pm_720" src="https://user-images.githubusercontent.com/4267904/31687084-200a53a8-b33d-11e7-924f-bffe8d49b647.png">

<img width="305" alt="screen_shot_2017-10-16_at_2 25 29_pm_720" src="https://user-images.githubusercontent.com/4267904/31687090-251aaef6-b33d-11e7-82e8-b62c54401598.png">

<img width="360" alt="screen_shot_2017-10-16_at_2 25 35_pm_720" src="https://user-images.githubusercontent.com/4267904/31687094-28a3259e-b33d-11e7-9cdf-13c808db1570.png">

<img width="360" alt="screen_shot_2017-10-16_at_2 25 46_pm_720" src="https://user-images.githubusercontent.com/4267904/31687102-2c44e124-b33d-11e7-927b-2a4ded224b73.png">

**Comment by jgiovanni** [comment]
http://recordit.co/Vedq62qSpC

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/18/17 - 10/18/17
Work session total: 2:19:31

Grand total: 9:43:33
