### ISSUE TITLE
Medical Release Redesign

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#785]
- Need a better way of communicating a lot of content.
 - Strategically order questions to get the most accurate and truthful answers from the user

Static prototype:
https://projects.invisionapp.com/share/QDDZDQVBW#/screens

Wireframes:

![medical release - step 1](https://user-images.githubusercontent.com/4267904/31640641-75408f9e-b294-11e7-9feb-f4f96034a369.png)
![medical release - step 1b](https://user-images.githubusercontent.com/4267904/31640642-7559edb8-b294-11e7-94e0-b13353a88ac6.png)
![medical release - step 2](https://user-images.githubusercontent.com/4267904/31640643-757002ba-b294-11e7-8cf7-f517855edd75.png)
![medical release - step 2c](https://user-images.githubusercontent.com/4267904/31640645-75872f4e-b294-11e7-832f-a904373a194d.png)
![medical release - step 2d](https://user-images.githubusercontent.com/4267904/31640646-75a4cc48-b294-11e7-90b3-5a17debda2c2.png)
![medical release - step 2g](https://user-images.githubusercontent.com/4267904/31640647-75c94780-b294-11e7-8c7b-90c50db17b5e.png)
![medical release - step 3](https://user-images.githubusercontent.com/4267904/31640648-75dc83b8-b294-11e7-9158-43482d39ffb6.png)
![medical release - step 4](https://user-images.githubusercontent.com/4267904/31640650-75feb5fa-b294-11e7-8576-dd5249b931d5.png)
![medical release - step 5](https://user-images.githubusercontent.com/4267904/31640651-7614af0e-b294-11e7-864c-280211f2ba65.png)
![medical release - step 6](https://user-images.githubusercontent.com/4267904/31640652-763c24b2-b294-11e7-9326-b8fa7f7074bd.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/18/17 - 10/18/17
Work session total: 4:07:46

Grand total: 4:07:46

**Comment by nkeena** [comment]
- [ ] Update Form Request Class @nkeena
- [ ] Back button is working on first step
- [ ] Still seeing the conditions and allergy list even if no is selected for everything on step 2
- [ ] The question "ARE YOU CURRENTLY TAKING ANY MEDICATION?" on conditions list and allergies list should be a new input and not carried over from step 2. Please see mockups below for correct label usage.
- [ ] Emergency contact step should use a single column layout for input fields
- [ ] Step indicator does not show last step

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/23/18 - 01/23/18
Work session total: 0:24:30

Grand total: 4:32:16

**Comment by nkeena** [comment]
- [ ] Add `takes_medication` column with migration
- [ ] Update design for medical releases list
- [ ] Pre-select radios on step 2 based on existence of conditions, allergies, and if the user takes medication.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/23/18 - 01/23/18
Work session total: 0:59:30

Grand total: 5:31:46

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/29/18 - 01/29/18
Work session total: 0:49:48

Grand total: 6:21:34
