### ISSUE TITLE
"Create or Skip" Fundraiser Step on Trip Registration

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#787]
### User Story

As a user who has just registered for a trip, I want the option to create a fundraiser or skip it until later so that I can get a fundraising page up and running.

### Acceptance Criteria

- [x] See a prompt after registering to create a fundraiser or skip it
- [x] If choosing to create, see a simple form to create fundraiser and get redirected to the fundraiser edit form.
    - Ideally only two fields would be needed: (1) Title, (2) URL slug
- [x] If choosing to skip, then redirect to reservation dashboard as usual

**initial prototype does not need to save data or redirect to the actual fundraiser edit form**

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/21/17 - 10/21/17
Work session total: 0:09:44

Grand total: 0:09:44

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/25/17 - 10/25/17
Work session total: 1:47:29

Grand total: 1:57:13

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/25/17 - 10/26/17
Work session total: 3:33:55

Grand total: 5:31:08

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/30/17 - 10/30/17
Work session total: 0:57:58

Grand total: 6:29:06
