### ISSUE TITLE
Errors showing on forms after successful submission

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#797]
There are several forms that are showing error messages like this after successfully submitting the form.

Group Request Submission:
<img width="872" alt="screen shot 2017-10-24 at 11 14 27 am" src="https://user-images.githubusercontent.com/4267904/31960793-b5615b84-b8ad-11e7-9e91-87e2a510b999.png">

Trip interest form:
<img width="584" alt="screen shot 2017-10-24 at 11 24 39 am" src="https://user-images.githubusercontent.com/4267904/31960923-148a8a36-b8ae-11e7-96fc-38acc2b06b8f.png">

Contact us form:
<img width="669" alt="screen shot 2017-10-24 at 11 23 35 am" src="https://user-images.githubusercontent.com/4267904/31960930-19e90372-b8ae-11e7-9e16-5109e4ff299e.png">

Speaker Request Form:
<img width="715" alt="screen shot 2017-10-24 at 11 26 55 am" src="https://user-images.githubusercontent.com/4267904/31960973-44517d9c-b8ae-11e7-84dc-483c215d2b0f.png">

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/24/17 - 10/24/17
Work session total: 1:03:04

Grand total: 1:03:04

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/25/17 - 10/25/17
Work session total: 2:37:05

Grand total: 3:40:09

**Comment by nkeena** [comment]
Error state doesn't seem to be showing but the helper text still displays after submission?
Contact form seems to be working though.

Trip interest:
![screen shot 2017-10-26 at 2 39 32 pm](https://user-images.githubusercontent.com/4267904/32078639-80fe63c2-ba5c-11e7-856d-f92689ef0c83.png)

Speaker request:
![screen shot 2017-10-26 at 2 43 58 pm](https://user-images.githubusercontent.com/4267904/32078647-863e1288-ba5c-11e7-9fc4-a04752bae840.png)

Group request:
![screen shot 2017-10-26 at 2 45 02 pm](https://user-images.githubusercontent.com/4267904/32078665-94591f48-ba5c-11e7-844b-1d7c143798f0.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/30/17 - 10/30/17
Work session total: 1:23:52

Grand total: 5:04:01
