### ISSUE TITLE
Group list in admin won't sort

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#799]
The sort direction is always set to `ASC` when a call is made to the API and won't change to `DESC`. Not sure why.

**Comment by nkeena** [comment]
This list has been behaving very strangely. Search wasn't working either until I added a `search()` method to the `GroupFilter` class which is already extending `Filter` with it's own `search()` method.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 10/25/17 - 10/25/17
Work session total: 0:41:25

Grand total: 0:41:25
