### ISSUE TITLE
Possible issue with Reservation Birth Dates changing

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#820]
Sunhee’s date of birth changed to this (Screen shot).

I keep trying to reset and it won’t allow me, it keeps switching to different dates

Her date of birth is: 06/06/1950

![screen shot 2017-11-06 at 3 59 01 pm](https://user-images.githubusercontent.com/4267904/32468916-1f0bac4a-c305-11e7-9ccf-bbbc34131ca9.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/07/17 - 11/07/17
Work session total: 0:19:24

Grand total: 0:19:24
