### ISSUE TITLE
Fixed Age Filter on Reservations is Effecting Search Results

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#823]
The age filter by default is set to:
```
age[]:0
age[]:120
```
This makes sense, but some reservations have invalid birthdates entered. This could be an issue that can't be avoided 100% of the time but because their birthdays are set to a future date, they are excluded from the search results by the default age settings.

We should set these to null and make sure these filters do not get applied unless an age range is explicitly set by the user.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/11/17 - 11/11/17
Work session total: 1:07:40

Grand total: 1:07:40
