### ISSUE TITLE
User street address not displaying in list view

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#824]
User address is showing on the details page but in the user list table those columns are blank.

<img width="961" alt="screen shot 2017-11-10 at 1 10 22 pm" src="https://user-images.githubusercontent.com/4267904/32679324-e398f618-c61a-11e7-8e3a-f314808eebcf.png">

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/21/17 - 11/21/17
Work session total: 0:04:05

Grand total: 0:04:05
