### ISSUE TITLE
Rooming Option Default not allowing Trip Reg Process to Continue

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#826]
I've encountered an error where the continue button is disabled until the user selects a different rooming option. Seems like a default selection does not enable the button.

![screen shot 2017-11-20 at 2 21 26 pm](https://user-images.githubusercontent.com/4267904/33048599-8868aeb6-ce10-11e7-9ab6-5ff398da0398.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/21/17 - 11/21/17
Work session total: 0:31:06

Grand total: 0:31:06
