### ISSUE TITLE
Can't remove group managers in admin

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#827]
When trying to remove a group manager from a group in the admin, I encounter this error in the console:

`Uncaught TypeError: this.managers.$remove is not a function`

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/21/17 - 11/21/17
Work session total: 0:01:16

Grand total: 0:01:16
