### ISSUE TITLE
Campanion Add Errors are not Displaying to the user

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#828]
This error message should be displayed to the user, but there is no notification indicating that the request can't be completed.

![screen shot 2017-11-20 at 5 08 45 pm](https://user-images.githubusercontent.com/4267904/33049575-9fdd1a6e-ce15-11e7-824c-bea4bad446dc.png)

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 11/21/17 - 11/21/17
Work session total: 0:07:08

Grand total: 0:07:08
