### ISSUE TITLE
Transaction Search does not seem to filter results

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#830]
Nothing seems to happen (results aren't filtered) when send a search request.

![screen shot 2017-11-30 at 3 11 27 pm](https://user-images.githubusercontent.com/4267904/33578398-41ac9730-d8fb-11e7-992b-0dcd529eb8e9.png)

**Comment by jgiovanni** [comment]
I fixed a related issue, where the amounts did not match the search results as they are saved in the db as integers. 
However, i could not resolve the search issue. i believe it has something to do with either the search function or the fields in the searchable array.

**Comment by nkeena** [comment]
Great on fixing that amount issue! Wow!

Weird, it seems like after the update extending the search method on the `Filter.php` class doesn't seem to be working :/

I'll take a look. I need to simplify the search anyway

**Comment by nkeena** [comment]
- [ ] Overwrite `search` method on `TransactionFilter` class.
- [ ] Simplify search by providing options to search specific columns

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 12/05/17 - 12/05/17
Work session total: 2:04:17

Grand total: 2:04:17
