### ISSUE TITLE
Redesign Traveler Information Form

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#842]
Currently this form feels crowded with the two column layout. Moving to a single column layout would reduce visual noise. Explanation text is also need to explain the reasons for collecting the following information.

Role selection should be moved to it's own step as it's not really related to personal information and should provide extensive explanation of role types and how roles are determined.

### Acceptance Criteria

- [ ] ~~Remove role selection~~
- [x] Single Column design
- [x] Explanation added to Home / Mailing address block:
 
`
We need your home or mailing address so we can send you important materials related to your trip. This information is also required for trip accommodation and transportation arrangements.
`

- [x] Checkbox confirming that contact information is accurate and up-to-date.
- [x] Validates confirmation checkbox as required
- [x] Show validation error messages below each input and make sure the highlight
- [x] DOB, Gender and martial status explanation text:

`
Knowing your age, gender and martial status is required to best place you on a team and arrange your accommodations.
`

- [x] Remove height and weight fields (no longer necessary)
- [x] Explain reason for shirt-size field

`
Let us know your shirt size so we can send you an exclusive team shirt!
`

**Comment by nkeena** [comment]
@jgiovanni I'm adding you to this issue so that you can look into this validation problem as well as make sure all validation message are displaying for each input and that every field is being highlighted.

This happens when checkbox is selected:

<img width="874" alt="screen shot 2018-01-17 at 5 01 20 pm" src="https://user-images.githubusercontent.com/4267904/35075479-129f8716-fba8-11e7-911f-b51e34038076.png">


Being that the new design makes the form scroll more vertically, if an error is at the top of the form, the user might not notice. Maybe having a sweet alert prompt show if there are validation errors to tell the user to check the form could be helpful?

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/17/18 - 01/18/18
Work session total: 2:16:48

Grand total: 2:16:48

**Comment by jgiovanni** [comment]
Those messages are generated by vee-validate, they aren't coming from the api.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/19/18 - 01/19/18
Work session total: 2:01:36

Grand total: 4:18:24
