### ISSUE TITLE
Deadline Agreement -> Requirements

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#844]
### User Story

As a user, I want know what documents are required to travel so that I know what kind of information I will need to provide.

### Acceptance Criteria

- [x] See list of travel requirements with due dates
- [x] User must agree to provide the information above before the given due dates or risk being dropped from the trip
- [x] Remove cost deadlines

**Comment by nkeena** [comment]
To clarify we want to rename the deadline agreement step to simply "Requirements". We only want the requirements and their deadlines listed, not the cost amounts and deadlines listed. Those will be on the new "financial agreement" step which will be the second to last step right before the payment screen.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/17/18 - 01/17/18
Work session total: 0:12:31

Grand total: 0:12:31
