### ISSUE TITLE
Payment Screen

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#845]
### User Story

As a user, I want pay my upfront costs with a credit card so that I can reserve my spot on the trip.

### Acceptance Criteria

- [x] See payment details screen as last step
- [x] See total amount due "now"
- [x] CC validates and charges the user
- [x] All validation and CC errors are displayed to the user
- [x] See loading screen while CC is charged and reservation is created

**Comment by nkeena** [comment]
To clarify, this screen should show a summary of what is DUE NOW and a payment form. Completing this step will create the reservation and verify and charge the credit card.

**Comment by jgiovanni** [comment]
Should the promo input be here? or should it be on another step?

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/17/18 - 01/17/18
Work session total: 1:17:23

Grand total: 1:17:23
