### ISSUE TITLE
Can't transfer a reservation - stops at assigning role

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#863]
Cannot set a role assignment to complete the reservation transfer process.

**Comment by nkeena** [comment]
The roles select is not populating with roles. The API all is successful and returning results but the input doesn't seem to get updated.

<img width="1436" alt="screen shot 2018-01-30 at 9 38 24 am" src="https://user-images.githubusercontent.com/4267904/35581682-679e76b6-05a1-11e8-945e-334ca9e812f0.png">

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/30/18 - 01/30/18
Work session total: 0:13:32

Grand total: 0:13:32
