### ISSUE TITLE
Groups not filtering on search

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#871]
When searching for a group in the `campaign-groups` component, the API call goes out but the list doesn't get filtered by the response.

<img width="1438" alt="screen shot 2018-01-30 at 9 34 31 am" src="https://user-images.githubusercontent.com/4267904/35581543-f5245060-05a0-11e8-96cb-0412a0ddfd4e.png">

**Comment by jgiovanni** [comment]
@nkeena There is an issue in the search function - specifically when dealing with relationship columns like `group.name`

**Comment by jgiovanni** [comment]
@nkeena I changed line 75 in `Filter.php` from `$col->orWhere(strrev($field), 'LIKE', "%$term%");` to `$col->where(strrev($field), 'LIKE', "%$term%");` I understand this affects every seach, so it might be best if you double check! 😄

**Comment by jgiovanni** [comment]
Because it is a nested query on a column, could it be that the first needs to be `->where` and others should be `->orWhere` ?

**Comment by nkeena** [comment]
Okay, I will double check. Since I upgraded to Laravel 5.4, it seems a lot of the search filters broke. This might be the reason why (kinda strange).

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 01/30/18 - 01/30/18
Work session total: 1:04:03

Grand total: 1:04:03
