### ISSUE TITLE
Swap fundraiser description components for Redactor

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#881]
@jgiovanni did an amazing job building out all these fundraiser components, but after implementing redactor with Angel House it's ease of use and simplicity are just so good.

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/05/18 - 02/06/18
Work session total: 2:43:49

Grand total: 2:43:49
