### ISSUE TITLE
Automatically scroll to top of update when selected

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#885]
When a user clicks "read more" on an update, the page should scroll to the top of that story. Right now, the user is forced to manually scroll upward to get to the beginning of the update

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/05/18 - 02/06/18
Work session total: 1:15:02

Grand total: 1:15:02
