### ISSUE TITLE
Capture Best Communication Time & Method

### ISSUE THREAD

**Issue by nkeena** [missions-me/missions#892]
### User Story

As a user, I want indicate on my reservation the best method and time to communicate with me so that Missions.Me staff can better assist me.

### Acceptance Criteria

- [x] See the follow on Trip Registration form:
    - Preferred Communication (checkboxes):
        - Phone Call
        - Text
        - Email
    - Timezone selection (should guess or use authenticated user's timezone)
    - Best time to reach you?
        - Morning
        - Afternoon
        - Evening
- [x] All inputs are required and should be located on the traveler's details page

- [x] Admins can edit or add the above data to any reservation

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/22/18 - 02/22/18
Work session total: 0:03:23

Grand total: 0:03:23

**Comment by jgiovanni** [comment]
via Hubstaff
User: Jerez Bain

Project: Missions.me - https://app.hubstaff.com/projects/120228
Date Range: 02/22/18 - 02/23/18
Work session total: 1:51:29

Grand total: 1:54:52
